### ISSUE TITLE
Arquivos do curso de HMTL e CSS

### ISSUE THREAD

**Issue by jos3s** [gustavoguanabara/html-css#1]
Professor, seria interessante adicionar nesse repositório os arquivos utilizados no seu curso de web do youtube, pois atualmente o link existente está quebrado.
[Curso de HTML5 - 03 - Como Funciona a Internet - by Gustavo Guanabara](https://www.youtube.com/watch?v=LMfeZ6XD0No&list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o&index=4)

**Comment by christyanbrayan** [comment]
@jos3s tbm acho.

Tô refazendo o curso pela 3ª vez, dessa vez 'commitando' a cada aula em um repositório, que vou tornar público quando terminar. Se estiver precisando, colaram um link novo desse pacote em algum comentário das primeiras aulas, mas claro que seria interessante se o Guanabara postasse também.

E caso precise dos arquivos do site pronto, tem alguns repositórios por aí e o meu daqui a alguns dias :)

**Comment by christyanbrayan** [comment]
@jos3s 
mas tbm há a questão que esse repositório foi pensado para o curso ministrado por ele em uma escola do RJ, e disponibilizado para quem quisesse também. Então caso ele vá liberar algo do curso de 2013 deve ser em um outro repositório

**Comment by jos3s** [comment]
Sim você tá certo, só queria informar sobre isso pois prejudica muito quem quer fazer o curso do YouTube

**Comment by gustavoguanabara** [comment]
Ótima sugestão! Vou procurar aqui nos meus backups os arquivos originais do curso e vou subir aqui no perfil do CursoemVideo que eu também criei.

**Comment by gustavoguanabara** [comment]
José, você ficou famoso! Por conta do seu pedido, acabei de gravar uma aula totalmente voltada para solucionar o seu problema.

É com grande orgulho que eu informo que o projeto total já está disponível no link abaixo

[Repositório do curso de HTML5 e CSS3](https://github.com/cursoemvideo/cursoemvideo-html5-css3)

**Comment by christyanbrayan** [comment]
#eutavala

**Comment by RichardSmanhoto** [comment]
#EuTavaLá

**Comment by LeonardoARGR** [comment]
#EuTavaLá

**Comment by FranciscoAntonioDomingosFilho** [comment]
#EuTavaLá

**Comment by fernandoarmonellifiedler** [comment]
#eutavala

**Comment by kazordoon** [comment]
#EuTavaLá

**Comment by carlosdaniel-cyber** [comment]
#EuTavaLá

**Comment by adrianomendoncaa** [comment]
#EuTavaLa

**Comment by cleysonsilvame** [comment]
#EuTavaLá

**Comment by duardobgf** [comment]
#EuTavaLá

**Comment by giliardipereira** [comment]
#EuTavaLa

**Comment by Fernandoff17** [comment]
#EuTavaLá

**Comment by httpLucasReis** [comment]
#EuTavaLá

**Comment by jos3s** [comment]
@gustavoguanabara muito obrigado professor ❣️🎉

**Comment by GuilhermeGuii** [comment]
#EuTavaLá, Guanabara muito obrigado por toda sua disposição de nos ensinar, tudo isso que ti faz por nós hoje no futuro será muito recompensador, eu lhe garanto!

**Comment by ItaloMedici** [comment]
UFC foi a melhor parteLKKKKKKKK #EuTavaLá

**Comment by claudomirocoutinho** [comment]
Cara umas das melhores coisas que já mim aconteceu, é uma satisfação conhecer cada um de vocês aprendendo demais, apesar que estou começando agora nessa área obrigado a todos

**Comment by fernandoamerico** [comment]
#EuTavaLa

**Comment by RodrigoPiropo** [comment]
#ToLaDenovo

**Comment by erikssonsantos** [comment]
#ToLaDenovo

**Comment by gustavoguanabara** [comment]
Olá @jos3s ! É com imenso prazer que informo que o pacote que você pediu já está aqui no GitHub. Para acessá-lo [clique aqui](https://github.com/cursoemvideo/cursoemvideo-html5)
