### ISSUE TITLE
Cadê o exercícios do módulo 02?

### ISSUE THREAD

**Issue by Jonas-petty** [gustavoguanabara/html-css#104]
A pasta dos exercícios do módulo 02 não está no repositório, porém no material em PDF 13 pede um tal de exercício 16.

**Comment by liraliraaa** [comment]
Exato! Também procurei os exercícios e PDFs das aulas do módulo 2 e não achei :/

**Comment by Henrick04** [comment]
Pois é estou parado no desafio 10 não há pasta e nada que faça referencia ao módulo 02.
