### ISSUE TITLE
Material do curso de HTML5 + CSS3 incompleto

### ISSUE THREAD

**Issue by camilacassimiro90** [gustavoguanabara/html-css#107]
Olá, querido prof!

Estão faltando exercícios do módulo I do curso de  HTML5 + CSS3. Poderia verificar, por favor?

Grata!

**Comment by michellealbertyne** [comment]
Como consigo o gabarito dos exercícios? sabem me dizer?

**Comment by camilacassimiro90** [comment]
> Como consigo o gabarito dos exercícios? sabem me dizer?

Seria isso aqui? https://github.com/gustavoguanabara/html-css/tree/master/exercicios/modulo-01

**Comment by Ondion** [comment]
Resolvido?

**Comment by PCMSS** [comment]
> Como consigo o gabarito dos exercícios? sabem me dizer?

Favor não fazer novas perguntas dentro de uma Issue já aberta.
Procurar se possui uma que atenda sua dúvida, caso não, abrir uma nova ISSUE.

R: Não possui gabarito para as questões no final dos PDFs das aulas, porém as respostas estão dentro do próprio PDF. Faça e depois corrija, assim você reforça as informações que você já tem e verifica as respostas corretas quando errar.

**Comment by Ondion** [comment]
🤖

**Comment by camilacassimiro90** [comment]
Vou fechar a issue, já que saíram os próximos módulos e a continuação dos exercícios. Bons estudos, galera!
