### ISSUE TITLE
ME AJUDA GUANABARA

### ISSUE THREAD

**Issue by pedrohenriquebraga** [gustavoguanabara/html-css#11]
Olá @gustavoguanabara , eu não estou recebendo as aulas diárias de html5, a última que eu tenho é a aula sobre negrito e Itálico. O que eu devo fazer?

**Comment by pedrohenriquebraga** [comment]
@cursoemvideo

**Comment by pedrohenriquebraga** [comment]
@gustavoguanabara

**Comment by gustavoguanabara** [comment]
Estamos passando por alguns problemas com o Vimeo, mas já coloquei novas aulas lá nas recompensas, ok? Pode ir lá, porque já saiu ;)

**Comment by pedrohenriquebraga** [comment]
> Estamos passando por alguns problemas com o Vimeo, mas já coloquei novas aulas lá nas recompensas, ok? Pode ir lá, porque já saiu ;)

Ok, muito obrigado!!
