### ISSUE TITLE
Quando o senhor vai atualizar as novas aulas de HTML5 na plataforma

### ISSUE THREAD

**Issue by Flavoide** [gustavoguanabara/html-css#115]
Guanabara, boa tarde!
existe uma previsão de quando será atualizado o curso de HTML com as novas aulas?

Obrigado!
Hoje estou no mundo da TI por sua causa ;)

**Comment by vinisantos7** [comment]
Bom Dia
Eu estava estudando ontem e vi as aulas novas do módulo 2 no site do CeV.

Bons estudos, Dev
