### ISSUE TITLE
Fala Profº Guanabara

### ISSUE THREAD

**Issue by santosvini** [gustavoguanabara/html-css#135]
Estou notando que o pessoal sente falta da estrutura montada dos exercícios e de alguns pdf's para estudar e também consultar, se caso precise de apoio, posso ajudar a ir adicionando, assim ja é uma forma de treinamento tbm.

Abs

**Comment by carolbalbs** [comment]
voce conseguiu encontrar onde estão os arquivos do ex022?

**Comment by santosvini** [comment]
> voce conseguiu encontrar onde estão os arquivos do ex022?

Ainda não cheguei no exercício, no módulo 2 ele so vai até o ex021, depois é o projeto, mas no github pessoal dele, tem os exercícios lá tbm, eu vi numa outra issue

**Comment by santosvini** [comment]
> voce conseguiu encontrar onde estão os arquivos do ex022?

https://github.com/professorguanabara/html-css/tree/master/exercicios

**Comment by santosvini** [comment]
Resolved
