### ISSUE TITLE
Imagens cap 19

### ISSUE THREAD

**Issue by Euridesb** [gustavoguanabara/html-css#138]
Boa Tarde 
comecei a primeira aula do cap. 19
e no repositório de html e css
não tem o exercício 22 para 
o download das imagens,

Obrigado 
Eurides Bonecher Filho

**Comment by santosvini** [comment]
Tem no repo dele pessoal professor guanabara

**Comment by Euridesb** [comment]
boa tarde
Já achei
Obrigado.
