### ISSUE TITLE
Pacotes-zip do projecto cordel

### ISSUE THREAD

**Issue by Rachidomar1523** [gustavoguanabara/html-css#140]

**Comment by rutebmg-coder** [comment]
Eu achei no desafio 12, modulo 12 --> I find in the desafio 12 modulo 2
https://github.com/gustavoguanabara/html-css/blob/master/desafios/modulo-02/d012/pacote-d012.zip

**Comment by Rachidomar1523** [comment]
Yes já o encontrei a bom tempo
Valeu
