### ISSUE TITLE
Atualizar links [PDF 01 - História da Internet]

### ISSUE THREAD

**Issue by dandrade0803** [gustavoguanabara/html-css#15]
__Professor @gustavoguanabara__ , 

Não consegui acessar nenhum dos vídeos(url) que estão no PDF. Na verdade, o link acaba no caracter anterior ao __?__

![image](https://user-images.githubusercontent.com/55857410/81489330-6c464080-924a-11ea-8995-bbf923445f37.png)

Assisti com esse link: https://youtu.be/cAwsLaO4HGQ

***
![image](https://user-images.githubusercontent.com/55857410/81489418-82083580-924b-11ea-91bf-6b040ca5d074.png)

Assisti com esse link: https://youtu.be/pKxWPo73pX0
***
![image](https://user-images.githubusercontent.com/55857410/81489434-b3810100-924b-11ea-896a-abe4bf56f269.png)

Assisti com esse link: https://youtu.be/k_inQhpKprg
***
![image](https://user-images.githubusercontent.com/55857410/81489464-065ab880-924c-11ea-82b2-f98be50ddfc2.png)

Assisti com esse link: https://youtu.be/rsFCVjr5yxc

**Comment by Rodrigojw2014** [comment]
@dandrade0803 parece que sim! Na aula de git ele acessa o link. E diz ser mesmo sobre a guerra fria. Espero que sua issue seja atendida! 🔥

**Comment by Rodrigojw2014** [comment]
@dandrade0803 Testei aqui e o link funciona normalmente e se encontra da mesma forma na barra de endereços. Acho que não tem nenhum problema no link

**Comment by jndrsn** [comment]
Estou acompanhando os videos do curso sobre GITHUB e não encontrei a pasta do Projeto Glass, alguem sabe onde encontro ?

**Comment by erasmo-ads** [comment]
@jndrsn Clica [aqui](https://drive.google.com/drive/folders/1ArEvSUSyDqgeQcIaTlX6aev_A6tkS_7Z?usp=sharing) para ter acesso ao Projeto Glass. Espero ter ajudado!

**Comment by Vbanety** [comment]
> Estou acompanhando os videos do curso sobre GITHUB e não encontrei a pasta do Projeto Glass, alguem sabe onde encontro ?

Tem um vídeo do curso em video, html e css onde há um link nos comentários do video.
Achei o link

**Comment by Vbanety** [comment]
> > Estou acompanhando os videos do curso sobre GITHUB e não encontrei a pasta do Projeto Glass, alguem sabe onde encontro ?
> 
> Tem um vídeo do curso em video, html e css onde há um link nos comentários do video.
> Achei o link

https://mega.nz/#!Pw00RDiK!2qmaoAhz7oJaYgk_cKXGlO7Yb-YeemHpwUZZV1VPdx8

**Comment by Rodrigojw2014** [comment]
@dandrade0803 Os links funcionam corretamente e já foi criado outro PDF dessa aula. 
Pode acessar pelo link do repositório: https://github.com/gustavoguanabara/html-css/tree/master/aulas-pdf

Favor @dandrade0803  feche sua Issue. Obrigado!
