### ISSUE TITLE
Desafios Modulo 3

### ISSUE THREAD

**Issue by SauloMaia01** [gustavoguanabara/html-css#150]
Bom Dia,

Onde estão os desafios do modulo 3, não estou achando ?

**Comment by santosvini** [comment]
Boa Tarde

o @gustavoguanabara explica nos vídeos das aulas como executar os desafios, eu fiz com a tela pausada e vendo como ele queria o resultado final, consegui executar, se for uma boa para você, tente assim

Abs

**Comment by SauloMaia01** [comment]
Obri gado pelas informações amigo, foi o que eu acabei fazendo.

**Comment by SauloMaia01** [comment]
> Boa Tarde
> 
> o @gustavoguanabara explica nos vídeos das aulas como executar os desafios, eu fiz com uma tela pausada e vendo como ele queria o resultado final, consegui executar, se para uma boa para você, tente assim
> 
> Abdômen

**Comment by SauloMaia01** [comment]
> Boa Tarde
> 
> o @gustavoguanabara explica nos vídeos das aulas como executar os desafios, eu fiz com uma tela pausada e vendo como ele queria o resultado final, consegui executar, se para uma boa para você, tente assim
> 
> Abdômen

Obrigado pelas informações amigo, foi o que eu acabei fazendo.
