### ISSUE TITLE
Aulas do modulo 3

### ISSUE THREAD

**Issue by joaopedrobenassi** [gustavoguanabara/html-css#153]
As aulas do curso em video no proprio site só tem ate o 20 e poucos, ja no youtube ja tem mais aulas, tem alguma previsao de quando estará completo na plataforma?

**Comment by DuelGD** [comment]
Olá, eles postam um capítulo ou mais inteiro no youtube para depois postarem no curso em vídeo, assim as aulas lá não ficam incompletas(ex: capitulo 10 tem 10 aulas, ai ficar só 5 e a pessoa n conseguir progredir + ou parar no meio de uma aula, etc..).

Mas sobre a previsão, não tem

**Comment by samillemachado** [comment]
Mandei email pra plataforma do Curso em Vídeo com a mesma dúvida e me responderam que em breve estará lá!
