### ISSUE TITLE
Cap 18 aula 06

### ISSUE THREAD

**Issue by Vinicius1980** [gustavoguanabara/html-css#156]
Olá Gafanhoto master.
Eu estou tendo problema com essa aula de hospedagem no Github Pages.
 Não estou conseguindo nem colocar o link no READ ME para funcionar, nem fazer o link do Projeto android seguindo a aula.
O senhor pode me ajudar, por favor!
Desde já grato

**Comment by Castro71** [comment]
> Olá Gafanhoto master. Eu estou tendo problema com essa aula de hospedagem no Github Pages. Não estou conseguindo nem colocar o link no READ ME para funcionar, nem fazer o link do Projeto android seguindo a aula. O senhor pode me ajudar, por favor! Desde já grato

Olá! abaixo deixarei uma print/vídeo com alguns cuidados para o READ ME e GitHub Pages!

READ ME:
[https://imgur.com/qGWimzS](url)

Github Pages:
[https://youtu.be/D7PVivfdqk0](url)

**Comment by Castro71** [comment]
Ambos os links não conseguem ser abertos se você apenas clicar sobre eles. Copie e cole na aba de pesquisa do seu navegador. O Vídeo está no youtube e a print no imgur (sites seguros).

**Comment by Vinicius1980** [comment]
@santosvini de cara nada acontece. Faço a aula normal, porém muita coisa ta diferente aqui. Tipo não aparece pra escolher a branch master no caso do projeto android eu uso a opção que tem "main", gera o link, porém quando vou testar o link da erro na página. Tanto no celular quanto no pc.
O link no "readme" tbm não rolou, apareceu no navegador a <tag>.
A única coisa que deu certo foi o primeiro exercício de hospedar o repositório todo, mas sem conseguir colocar o link do exercício.

**Comment by Vinicius1980** [comment]
> O que acontece quando vc tenta hospedar no gh-pages?
de cara nada acontece. Faço a aula normal, porém muita coisa ta diferente aqui. Tipo não aparece pra escolher a branch master no caso do projeto android eu uso a opção que tem "main", gera o link, porém quando vou testar o link da erro na página. Tanto no celular quanto no pc.
O link no "readme" tbm não rolou, apareceu no navegador a .
A única coisa que deu certo foi o primeiro exercício de hospedar o repositório todo, mas sem conseguir colocar o link do exercício.

**Comment by Vinicius1980** [comment]
@santosvini de cara nada acontece. Faço a aula normal, porém muita coisa ta diferente aqui. Tipo não aparece pra escolher a branch master no caso do projeto android eu uso a opção que tem "main", gera o link, porém quando vou testar o link da erro na página. Tanto no celular quanto no pc.
O link no "readme" tbm não rolou, apareceu no navegador a .
A única coisa que deu certo foi o primeiro exercício de hospedar o repositório todo, mas sem conseguir colocar o link do exercício.

**Comment by Vinicius1980** [comment]
@Castro71 não consegui acessar os links

**Comment by santosvini** [comment]
> @santosvini de cara nada acontece. Faço a aula normal, porém muita coisa ta diferente aqui. Tipo não aparece pra escolher a branch master no caso do projeto android eu uso a opção que tem "main", gera o link, porém quando vou testar o link da erro na página. Tanto no celular quanto no pc. O link no "readme" tbm não rolou, apareceu no navegador a . A única coisa que deu certo foi o primeiro exercício de hospedar o repositório todo, mas sem conseguir colocar o link do exercício.

Entendi, pode ser que a branch esteja diferente, talvez vc tenha criado como master e no github é main, verifica isso pfv, se for o caso envia o print no quote aqui como resposta pfv!

**Comment by santosvini** [comment]
> > @santosvini de cara nada acontece. Faço a aula normal, porém muita coisa ta diferente aqui. Tipo não aparece pra escolher a branch master no caso do projeto android eu uso a opção que tem "main", gera o link, porém quando vou testar o link da erro na página. Tanto no celular quanto no pc. O link no "readme" tbm não rolou, apareceu no navegador a . A única coisa que deu certo foi o primeiro exercício de hospedar o repositório todo, mas sem conseguir colocar o link do exercício.
> 
> Entendi, pode ser que a branch esteja diferente, talvez vc tenha criado como master e no github é main, verifica isso pfv, se for o caso envia o print no quote aqui como resposta pfv!

![image](https://user-images.githubusercontent.com/46813491/148058726-d35cb447-cdd6-4aeb-a41c-b22d0bf7dd0d.png)

**Comment by Vinicius1980** [comment]
@santosvini Eu modifiquei no "options" do github desktop e agora aparece pra mim master, quando crio um novo repositório. Porém o erro em carregar a página persiste. # #

**Comment by santosvini** [comment]
> @santosvini Eu modifiquei no "options" do github desktop e agora aparece pra mim master, quando crio um novo repositório. Porém o erro em carregar a página persiste. # #
> 
> Tentei carregar o print da falha de carregamento, mas não consegui.
> 
> Aparece: 404 There isn't a GitHub Pages site here. If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

vc fez o passo do print da imagem?

**Comment by Castro71** [comment]
> @Castro71 não consegui acessar os links

Copia e cola em outra aba do navegador

**Comment by santosvini** [comment]
> > @Castro71 não consegui acessar os links
> 
> Copia e cola em outra aba do navegador

Eu tentei reproduzir assim, tbm n abre

**Comment by Vinicius1980** [comment]
@santosvini não pesquisei como posta aqui. Eu  não achei o "quote" q vc disse.

**Comment by santosvini** [comment]
> @santosvini não pesquisei como posta aqui. Eu não achei o "quote" q vc disse.

Qual quote? se for para colocar a img aqui, tira o print e cola com controlV, o github ja faz o processo, rs

**Comment by lucianononato** [comment]
fala Vinicius estava com o mesmo problema que você, se não tiver resolvido me avise que eu ajudo você.

**Comment by Vinicius1980** [comment]
@lucianononato Olá foi resolvido, porém fiz tantas modificações e excluí e incluí tantas vezes o repositório, que na verdade nã sei qual ação que realmente foi efetiva. Caso vc queira me ajudando a entender o que pode ter sido, eu vou curtir, pq odeio essa sensação de não saber o que resolveu. E obrigado pela atenção
