### ISSUE TITLE
Curso de PHP, Java e Python no GitHub

### ISSUE THREAD

**Issue by Eduardo499** [gustavoguanabara/html-css#16]
Olá, gostaria saber se no futuro, você poderia colocar os cursos de PHP, Python e Java no GitHub. Eu achei bem legal os PDF's do curso de HTML5 + CSS3, depois  que terminar vou ver os de JavaScript. Adeus!

**Comment by matheusfelipeog** [comment]
Como não tem previsão disso acontecer, até lá você pode conferir o repo do curso de python que criei na época que estudava com ele: [Curso em Vídeo Python 3](https://github.com/matheusfelipeog/curso-em-video-python3)

**Comment by Rodrigojw2014** [comment]
@Eduardo499 Favor feche sua Issue visto que o propósito das issues é sobre o curso de html-css. Gratissímo

**Comment by irvinglucas** [comment]
> @Eduardo499 Favor feche sua Issue visto que o propósito das issues é sobre o curso de html-css. Gratissímo
Meu caro, que bom que você aprendeu a usar as issues! Porém, muita gente ativou as notificações do repositório, e com isso, emails e mais emails estão chegando com todas as suas msgs; Dá uma maneirada ai porque tá complicado abrir 20 emails com a mesma msg. Deixa a moderação ou o @gustavoguanabara resolverem isso ai. Valeu!!!

**Comment by Rodrigojw2014** [comment]
@irvinglucas A maioria esquece de fechar suas issues, estou apenas ajudando a relembrar. Não sou moderador estou apenas tentando ajudar a filtrar e minimizar as abertas. Pois também acompanho as aulas

**Comment by Eduardo499** [comment]
> @irvinglucas A maioria esquece de fechar suas issues, estou apenas ajudando a relembrar. Não sou moderador estou apenas tentando ajudar a filtrar e minimizar as abertas. Pois também acompanho as aulas

Ok
