### ISSUE TITLE
Problemas com o GitHub

### ISSUE THREAD

**Issue by carloshmbrito** [gustavoguanabara/html-css#182]
Não estou conseguindo publicar o repositório para o github.com. No GitHub Desktop está tudo ok, mas quando tento publicar para criar o repositório remoto sempre aparece o seguinte erro:

> Enumerating objects: 123, done.
> Counting objects: 100% (123/123), done.
> Delta compression using up to 2 threads
> Compressing objects: 100% (109/109), done.
> error: RPC failed; curl 56 Send failure: Connection was reset
> send-pack: unexpected disconnect while reading sideband packet
> Writing objects: 100% (123/123), 14.38 MiB | 48.00 KiB/s, done.
> Total 123 (delta 11), reused 0 (delta 0), pack-reused 0
> fatal: the remote end hung up unexpectedly
> Everything up-to-date

Alguma forma para resolver?

**Comment by joaomiguel2006** [comment]
nao tem como resolver

**Comment by carloshmbrito** [comment]
> nao tem como resolver

Poxa vida. Obrigado pela resposta.
