### ISSUE TITLE
Problemas ao tentar acessar exercícios pelo github

### ISSUE THREAD

**Issue by joaomouram** [gustavoguanabara/html-css#183]
sempre que eu tento acessar meus exercícios na nuvem, igual o Gustavo faz nas aulas 5 e 6 do capítulo 19 do módulo 3, um erro aparece dizendo que o site não foi encontrado, o que poderia ser?

**Comment by ThiagoAlb** [comment]
As vezes tem que esperar um pouco para carregar o site no Github Pages. Ainda não cheguei nessa aula, mas tava com esse problema agora de tarde e uma parte dele foi porque tinha que esperar carregar.

Tenta dar mais detalhes ou tirar um print pra postar aqui e a gente tentar te ajudar.

**Comment by joaomouram** [comment]
> 

Assim, na questão de esperar eu acredito que não seja, sabe? Nunca consegui acessar os projetos que eu fiz pela hospedagem do GitHub, estou tentando a uns seis dias e nada.
Toda vez que eu tento acessar eles aparece isso:
![Captura de Tela (30)](https://user-images.githubusercontent.com/100963631/157731398-16ac8174-4431-416b-814b-eb24b2308744.png)

**Comment by ThiagoAlb** [comment]
Eu vi umas pessoas falando para fazer o seguinte:
No "Branch" troca de "gh-pages" para "main" e na opção de lado "root" você vai manter como está. Depois aperta "save" e espera uns minutos.
Já tentou isso?

**Comment by joaomouram** [comment]
desculpa a demora pra responder, eu fiquei um pouco ocupado
FUNCIONOU!!! mt obrigado amigo, sucesso aí pra vc

**Comment by ThiagoAlb** [comment]
Por nada, João. 👍
Sucesso pra você também!
