### ISSUE TITLE
Pdf do Modulo 3

### ISSUE THREAD

**Issue by bielgeri** [gustavoguanabara/html-css#190]
Estou acompanhando o modulo 3 o curso de HTML e CSS e não achei os arquivos em pdf dos capítulos depois do 20, alguém sabe onde tem?

**Comment by ThiagoAlb** [comment]
Parece que ainda não foram disponibilizados.

**Comment by felipeecoelho** [comment]
Eu também não encontrei! O Guanabara não comentou á respeito! Quando será disponibilizado o material? E quando será dada a sequência no curso para os próximos capítulos e módulos? Salva nóis Guana!

**Comment by BenjamimCS** [comment]
Pessoal, na Issue https://github.com/gustavoguanabara/html-css/issues/357 há uma solução. Seria bom fechar esta Issue por já ser repitida, vamos manter somente a https://github.com/gustavoguanabara/html-css/issues/357 com a solução temporária.
