### ISSUE TITLE
Não achei o desafio 13 do modulo 3

### ISSUE THREAD

**Issue by SauloJustiniano1** [gustavoguanabara/html-css#194]
## Dúvida do Módulo 3

* Não achei o desafio 13 do modulo 3, alguém sabe onde posso encontrar?

**Comment by BenjamimCS** [comment]
Realmente não tão aqui, muita gente tá tendo esse problema. Na verdade os demais desafios estão no outro perfil dele, aquele que ele criou em vídeo:
[https://github.com/professorguanabara](https://github.com/professorguanabara)

Os desafios lá não estão organizados por módulo, mas eu acho que seja esse:
[https://github.com/professorguanabara/html-css/tree/master/desafios/d013](https://github.com/professorguanabara/html-css/tree/master/desafios/d013)
Seria esse?

**Comment by SauloJustiniano1** [comment]
Obrigado!
