### ISSUE TITLE
Não consegui hospedar meu site

### ISSUE THREAD

**Issue by Rommendes** [gustavoguanabara/html-css#204]
Não consegui hospedar meu site! 
Help!!!

**Comment by jonasmatheus** [comment]
Olá, posso tentar te ajudar!

**Comment by Rommendes** [comment]
Olá Jonas! Se vc puder...blz
Travei!

**Comment by jonasmatheus** [comment]
Me chama no Whats: (19) 98125-6150

**Comment by Rommendes** [comment]
ok

**Comment by BenjamimCS** [comment]
Poderia, por favor, detalhar melhor o ocorrido? Fica difícil descobrir o que possa ser assim em poucas palavras,

**Comment by BenjamimCS** [comment]
> Fiz essas capturas de tela.
> 
> ![Captura de tela 2022-04-19 103713](https://user-images.githubusercontent.com/96451367/164043017-fa081edc-1dee-4fbc-bc9c-dc5a6c8d9a4e.png) ![Captura de tela 2022-04-19 103841](https://user-images.githubusercontent.com/96451367/164043035-e738dafb-f41c-429c-8b97-4de82b76c652.png)

Na verdade ele já está hospedado porém está em outra `branch`, note a `branch` usada ali na aba de mesmo nome onde aponta para a `branch` `gh-pages`. Essa `branch` é criada pelo próprio GitHub Pages, só troque para sua principal, ou para que contenha os seus arquivos.

**Comment by Rommendes** [comment]
consegui!! Vlw
