### ISSUE TITLE
Capitulo 18 aula 06 - Publicar o repositório não funcionou.

### ISSUE THREAD

**Issue by deveduardoprado** [gustavoguanabara/html-css#208]
Bom dia, seguindo a aula tentei publicar no pages o repositório. Indo em pages, escolhendo um tema e salvando e beleza, a página "principal" foi publicada, ficando dev.eduardoprado.github.io/html-css/   . Essa publicou, mas as de mais onde teria por exemplo html-css/exercicios/ex001/index.html  podendo ver os exercícios e tudo mais publicados, da erro 404 e não aconteceu a publicação como aconteceu na aula em vídeo.
    Alguém teve o mesmo problema? sabem como resolver?
![Screenshot_1](https://user-images.githubusercontent.com/103898346/163814429-8e56e054-a08e-4ac7-9459-fc42bfb87b5e.png)

obrigado. :)

**Comment by Rommendes** [comment]
Também tive o mesmo problema, mas não consegui resolver. Alguma dica?

**Comment by BenjamimCS** [comment]
Ao configurar o Github Pages o padrão é ele mesmo criar uma `branch` chamada `gh-pages` onde irá conter o conteúdo do site. Basta mudar para a `main` ou `master`, a `branch` que realmente contém seus arquivos.

Recomendo dá uma lida na documentação do [GitHub Pages](github.com/en/pages "GitHub Pages Documantation - GitHub Docs") pra você entender melhor.

**OBS.**: caso seja essa a solução considere essa Issue encerrada. Então, por favor, feche-a, muitos não estão as fechando e tá gerando um acúmulo de Issue aberta já resolvida.

**Comment by deveduardoprado** [comment]
Olá, funcionou sim,
muito obrigado.

só agora q ficou sendo acessivel apenas colocando a palavra EXERCICIOS em maiúsculo na url, ja tentei renomear a pasta local para exercicios em minúsculo comitar e depois fiz o push. mas n alterou no repositório, no repositório ficou zuado com uma pasta a mais.

mas enfim, funcionou a dica. muito obrigado, vou fechar essa issue.

se tiver uma dica pra resolver esse lance do maiúsculo minúsculo me fala no email: dev.eduardoprado@gmail.com

abraço e bons estudos a todos :)
