### ISSUE TITLE
Problema durante o commit

### ISSUE THREAD

**Issue by yamilaschuarstz** [gustavoguanabara/html-css#210]
Olá! Estou tendo problemas em dar commit pro repositório remoto. Primeiro aparece assim:
![erro1](https://user-images.githubusercontent.com/104037265/165398536-2a2e9f6c-1134-4560-b998-c9100aae5295.png)

E quando clico em Pull origin, aparece essa mensagem:
![erro2](https://user-images.githubusercontent.com/104037265/165398661-881429ed-3618-426f-be2e-68af9bb9da8e.png)

Estou sem entender o que aconteceu!!

**Comment by estevaopolli** [comment]
Olá boa tarde Yamila, dei uma pesquisada no seu problema e acho que encontrei a resposta.
No seu github desktop pressione Ctrl + ' (ou vá na aba Repository + Open in command prompt) isso vai abrir um CLI então você digite "git config --global pull.ff true" caso não funcione tente outra opção que aparece no erro.

Vou deixar o print da resposta aqui caso entenda inglês
![imagem_2022-04-27_121035871](https://user-images.githubusercontent.com/101600957/165551035-650b413b-4f6e-4263-ad4f-9ed09b892c59.png)

**Comment by yamilaschuarstz** [comment]
> Olá boa tarde Yamila, dei uma pesquisada no seu problema e acho que encontrei a resposta. No seu github desktop pressione Ctrl + ' (ou vá na aba Repository + Open in command prompt) isso vai abrir um CLI então você digite "git config --global pull.ff true" caso não funcione tente outra opção que aparece no erro.
> 
> Vou deixar o print da resposta aqui caso entenda inglês ![imagem_2022-04-27_121035871](https://user-images.githubusercontent.com/101600957/165551035-650b413b-4f6e-4263-ad4f-9ed09b892c59.png)

Olá! Funcionou, muito obrigada pela ajuda!
