### ISSUE TITLE
Módulo 1 - Capítulo 8 - Aula 04 e  - Ajuda por favor :)

### ISSUE THREAD

**Issue by marco-a-marini** [gustavoguanabara/html-css#215]
Pessoal, já refiz o código olhei comparando com o do Guanabara e não consigo deixar igual.
No Módulo 1 - Capítulo 8 - Aula 04, no final dessa aula, quando o professor vai para o item abreviações e ele envelopa o HTML e o CSS para quando passar o mouse por cima aparecer o significado, no meu ficam os pontinhos embaixo, mas quando eu passo o mouse por cima nada acontece. Alguém teve esse problema? Soube resolver?
Desde já meu muito obrigado!

**Comment by VagMJB** [comment]
Tens como fazer uma foto no tej código. 

Eu fiz e não teve nenhum problema.

Estás a usar que navegador?

**Comment by marco-a-marini** [comment]
Vag, obrigado por escrever... exclui o arquivo, digitei todo de novo e deu certo... com certeza algum detalhe que eu não prestei atenção.
Sou da área de humanas e vou migrar minha carreira para informática, e uma coisa que percebi é que a atenção tem que ser 100%, pois uma vírgula, um parênteses errado dá erro.
Muito obrigado por sua mensagem.

**Comment by VagMJB** [comment]
Marco Tens razão, ao digitar um código devemos ter maior atenção.
