### ISSUE TITLE
Problema no Desafio do projeto Android, imagens vazando.

### ISSUE THREAD

**Issue by jharbes** [gustavoguanabara/html-css#216]
fiz o desafio do projeto android, ao testar no navegador, mesmo no tamanho de celular o site ficou ok, mas ao acessar pelo cel ficou sobrando espaço no lado direito e duas imagens vazaram. alguem imagina como poderia ser corrigido isso? obrigado.

segue link para analise:

https://jharbes.github.io/projeto-android/

**Comment by Al1son** [comment]
O meu esta acontecendo a mesma coisa.

**Comment by bernarenko** [comment]
Não tenho certeza se entendi direito qual seu problema, porém fiz uma mudança dento do seletor img{}, mudando o elemento 'display: flex;' para 'display: block;' e não tenho imagens vazando no meu celular.

Também remove o min-width pois ele não possui função, ficando assim:

```
img {
    margin: auto;
    display: block;
}
```
Se tiver resolvido seu problema, não esquece de fechar a issue.

**Comment by brunoeduaardo** [comment]
Boa noite!

Resolvi definindo o width da imagem em 100% assim ele força a imagem a ocupar 100% da largura da div em que ela está dentro (a section, no seu caso). Segue abaixo Screenshot do seu projeto com width adicionado pelo DevTools do Chrome e outra Screenshot com a Section em destaque, para você entender o raciocínio

![image](https://user-images.githubusercontent.com/82247602/172513130-c201c3f8-fc07-426e-a86a-976ba1f885e7.png)

![image](https://user-images.githubusercontent.com/82247602/172513309-de6ac070-7c1b-4b13-828a-f2465973fd9d.png)

Caso tenha mais alguma questão, pode chamar, meus contatos estão no meu perfil. Não garanto que sei tudo, mas vou tentar resolver hehe

Se puder, peço para marcar a Issue como resolvida caso seu problema tenha sido resolvido

**Comment by jharbes** [comment]
perfeito mano! deu certo! mto obg pela ajuda!!

**Comment by BenjamimCS** [comment]
> perfeito mano! deu certo! mto obg pela ajuda!!

Que bom ter resovlido seu problema.
@jharbes  Se a Issue for resolvida, por favor, feche a Issue, há diversas Issues resolvidas em abertos. Isso também ajuda a galera que tenha um problema similar. Grato.
