### ISSUE TITLE
Curso de HTML5 e CSS3

### ISSUE THREAD

**Issue by VagMJB** [gustavoguanabara/html-css#218]
Saudações pessoal. 
Preciso de ajuda, eu gostaria de saber qual a tag que devo usar para colocar um ícone em algum título, ou em um texto.

Sei que para mudar um fivicon, usa-se a tag link:favicon

E se for em algum texto??

**Comment by VanderleiSantanaTI** [comment]
Boa noite experimenta usar envelopar numa tag explo  <div  class=" *** ">Título</div>
vá no style
div. ***  : :  after{
content : ' \00a0\colocar aqui o cód. do ícone ;
}
