### ISSUE TITLE
Curso de HTML5 e CSS3

### ISSUE THREAD

**Issue by VagMJB** [gustavoguanabara/html-css#219]
Saudações pessoal. 
Preciso de ajuda, eu gostaria de saber qual a tag que devo usar para colocar um ícone em algum título, ou em um texto.

Sei que para mudar um fivicon, usa-se o link:favicon

E se for em algum texto??

**Comment by leobarbosas** [comment]
boa tarde, ícone em um texto não é muito comum, o que você pode colocar é um emoji, não sei se resolveria seu problema

**Comment by VagMJB** [comment]
Na verdade eu preciso colocar o ícone do Facebook, em um texto.

**Comment by leobarbosas** [comment]
já tentou usar o img e chamar o ícone?

**Comment by mikeafsilva** [comment]
Se for uma lista, você pode usar usar a imagem no lugar do list-decoration padrão. Posiciona os dois inline-block dentro da mesma div, ou se estiver separada, usa o float, ou flexbox

**Comment by VagMJB** [comment]
> já tentou usar o img e chamar o ícone?

Já consegui. 
Obrigado!
