### ISSUE TITLE
Treinar Replicando Sites

### ISSUE THREAD

**Issue by mikeafsilva** [gustavoguanabara/html-css#220]
Fala galera, tudo certo? Então, fiz o curso de HTML e CSS, e estou fazendo outro curso pela Udemy. Mas antes de avançar pra Javascript, gostaria de treinar meu HTML e CSS pra que ele fique impregnado na minha cabeça e eu não "esqueça" enquanto estiver focado em JS. O ponto é: Gostaria de treinar replicando sites, entendendo como eles funcionam e aplicando, do zero, uma réplica deles. Eu teria algum problema com direitos autorais se publicar no github pages? Ou deveria manter fora de um repositório?

**Comment by FelipeCostaMartins** [comment]
Se você criar seu próprio código do zero sem copiar o site original e desde que não tenha nenhuma imagem ou vídeo com direitos autorais você pode publicar no github sem problemas :D mesmo que você esteja tentando 'copiar' a interface
