### ISSUE TITLE
Imagem e Texto

### ISSUE THREAD

**Issue by leobarbosas** [gustavoguanabara/html-css#224]
Bom dia, gostaria de saber como faço para colocar uma imagem do lado esquerdo e um texto do lado direito, tenho que definir tanto o texto quanto a imagem com algum display? 
Obrigado.

**Comment by mikeafsilva** [comment]
Você pode colocar ambos dentro de uma div, ou section, e colocar eles display inline-block, assim você consegue usar a caixa da div, ou da section, como base de alinhamento. Também dá pra usar flexbox ou grid, mas ai tu vai ter que pesquisar à parte, porque não é um conteúdo que tem no curso

**Comment by leobarbosas** [comment]
Obrigado, ai eu posso colocar alguma opção pra alinhamento?

**Comment by mikeafsilva** [comment]
Pode usar o vertical-align pra alinhamento vertical, pra alinhamento horizontal tu pode usar width, height pra definir o tamanho das caixas dentro da div, e depois usar padding e margin pra separar elas. Não lembro se dá pra usar o align-items sem flexbox. Ai vai do que tu quer fazer com a imagem e o texto. Também dá pra colocar imagem e texto dentro de uma mesma classe e usar a propriedade float pra colocar imagem e texto do lado um do outro. Sugiro que tu dê uma pesquisada sobre alinhamento de caixas, é sempre bom ter uma outra visão além do que o Guanabara explica, às vezes uma didática diferente pode fazer você entender o conceito, e a do guanabara entender o uso, e vice-versa. Também seria interessante pesquisar sobre flexbox, grid e propriedade float, são muito usados nos sites, principalmente grid e flexbox. É um pouco complexo de entender no começo, eu mesmo ainda tenho dificuldades, mas é só questão de prática pra saber quando propriedade e parâmetro usar para cada caso. O lance é sempre jogar no youtube e google a dúvida e ver 2/3/4/5 maneiras diferentes de fazer

**Comment by leobarbosas** [comment]
Muito obrigado.
