### ISSUE TITLE
HTML5 Semântico

### ISSUE THREAD

**Issue by mikeafsilva** [gustavoguanabara/html-css#227]
Fala galera. Uma dúvida que eu tenho, e chega até ser algo irônico. Aprendemos com o Guanabara, e em todos os cursos de desenvolvimento web sobre semântica HTML5, sobre não usar div por conta do valor semântico. Mas ao abrir sites como o G1, Netshoes, e até mesmo o próprio site da w3schools, percebo que eles não usam main, section, article, e usam apenas div. Seria algum conceito mais avançado de HTML5? Preguiça dos desenvolvedores? Porque como são sites grandes e que o SEO do google puxa de primeira, não deveriam estar semanticamente corretos? Pior ainda a w3schools, que é o site que é usado como base, e recomenda o uso de tags semânticas, mas não usa elas. Alguém tem uma explicação real, sem hipóteses?

**Comment by FelipeCostaMartins** [comment]
Acredito que ainda vemos tantos códigos utilizando as ''divs'' de forma errada por causa do costume ao utilizar elas assim nas versões anteriores do HTML mas com o tempo tende a diminuir cada vez mais essa pratica. Outro motivo pode ser por culpa dos frameworks que já vem com templates prontos e acabam criando várias divs como no wordpress e deixa o código bagunçado. Nunca tinha parado pra pensar nisso achei até engraçado kkk espero ter ajudado :D

**Comment by SamuelItalo** [comment]
Fala @mikeafsilva, blz? Cara sem hipótese acredito que não tem como agente chegar em um raciocínio rsrs, mais acredito que seja por conta de códigos antigos, feitos em HTML4  e pela densidade de linhas que esses sites tem creio que não seja viável para eles refazer de forma semântica. Traduzindo, já que ta assim, deixa assim mesmo... kkk
