### ISSUE TITLE
Uso de <br> para criar uma linha em branco no primeiro desafio

### ISSUE THREAD

**Issue by guilhermeluciosilva** [gustavoguanabara/html-css#23]
Olá Professor, procurei em outras Issues e não achei, peço desculpas se já respondeu, mas em seu material de html e  css, no capítulo 05 ele passa a seguinte mensagem:

![image](https://user-images.githubusercontent.com/61800391/85320574-a9ccf900-b499-11ea-91bd-6f57c4a37300.png)

e no mesmo capítulo ele pede para realizar o desafio número 01, como a imagem a baixo demonstra:

![image](https://user-images.githubusercontent.com/61800391/85320686-d4b74d00-b499-11ea-9e3e-6ef55757db52.png)

O desafio no entanto é esse:

![image](https://user-images.githubusercontent.com/61800391/85320763-f87a9300-b499-11ea-97ed-e112b4aea39f.png)

Só que eu ainda não tenho conhecimento de como gerar uma linha em branco sem usar o <br> para quebrar, e por conta disso acabei utilizando o comando para cumprir o exercício. 

Se possível gostaria de ter acesso a resolução dos desafios para poder ver quais métodos posso utilizar. 
Ainda não avancei os capítulos, acredito que nos próximos deva ter a resposta.
Estou deixando essa observação que pode causar duvida nas pessoas. 

Um grande abraço!

**Comment by duardobgf** [comment]
Eu acho que ele está fazendo uma crítica a quem usa vários `<br>`, acredito que não há problema em usar somente um **neste exercício**, já que ele ainda não ensinou como fazer isso em CSS.

**Comment by guilhermeluciosilva** [comment]
é vdd, mas me forçou a ir atras do CSS mesmo antes, mas acho que você já responde a minha pergunta. Vlw man.

**Comment by Rodrigojw2014** [comment]
@guilhermeluciosilva muitos elementos são em bloco. Assim como o elemento P de paragrafo e H1 de título ele automaticamente faz um espaço em branco entre outro bloco. Então possivelmente o exercício há dois blocos. Só precisa descobrir qual elementos ele usou para criar esses blocos e reproduzir

**Comment by Jurubebs** [comment]
@guilhermeluciosilva Eu também fiquei na dúvida nisso, coloquei dois parágrafos, um para o primeiro bloco e outro para o segundo. Não sei se seria pra ser assim, mas coloquei algumas quebras de páginas depois dos números. Por exemplo: *Um <br>** Dois <br>... e assim sucessivamente. Não sei se seria o correto, mas fiz do jeito que consegui com o que eu lembro. espero que seja assim kkk
