### ISSUE TITLE
Desafio Android

### ISSUE THREAD

**Issue by RodrigoM1576** [gustavoguanabara/html-css#236]
estou tendo problema no projeto, a fonte android não está carregando, somente a cursiva, abaixo as linhas de codigo referente a fonte:

@font-face {
    font-family:"Android";
    src: url("/fontes/IDroid.otf") format("opentype");
    font-weight: normal;
}

:root{
    --fonte-android:'Android',cursive; 
}

main h1{
    color: var(--cor5);
    font-family:var(--fonte-android);
    margin: 10px;
}

**Comment by santosvini** [comment]
https://github.com/santosvini/projeto-android/blob/main/style/style.css

**Comment by LcGMartins** [comment]
Também estou com o mesmo problema.

**Comment by BenjamimCS** [comment]
> Também estou com o mesmo problema.

Vejam o direcionamento do arquivo. Boa parte das tecnologias usam o direcionamento/estrutura de pastas dos modelos Unix e Linux (que segue ele, enfim...).

Por exemplo: você colocou `/fontes/IDroid.otf`. Isso quer dizer que você está pedindo que procure na pasta raíz do sistema. Caso seu arquivo de estilo esteja em uma pasta de estilo use `../` para voltar para a pasta/diretório anterior. Caso não funcione, tente `./`, ou `../../`. Qualquer coisa só perguntarem, ou melhor, pesquisem sobre ou façam o curso de Linux do Guanabara que já dá o chão.
Espero ter ajudado!

**OBS.:** caso tenha resolvido o seu problema, por favor, feche esta Issue, há muitas Issues terminadas ainda em aberto por arqui. Se puder, dê um retorno ou só feche-a. Obrigado!
