### ISSUE TITLE
Modulo 4 

### ISSUE THREAD

**Issue by KallelCHZS** [gustavoguanabara/html-css#240]
Como faço para baixar o desafio 13?

**Comment by BenjamimCS** [comment]
Você pode clonar o outro repositório do Guanabara, esse aqu: https://github.com/professorguanabara/html-css e navegar até os desafios.
Caso queira para achar resposta, recomendo que esfrie a cabeça e tente denovo e pratique mais que você consegue meu caro, mas a escolha é sua.

**OBS.:** caso seja essa a solução, por favor, feche a Issue, há muitas Issues terminadas ainda em aberto. Grato.
