### ISSUE TITLE
titulo do reposítório diferente "ex002/imagens"

### ISSUE THREAD

**Issue by DevMarceloCampelo** [gustavoguanabara/html-css#250]
Boa noite, Professor Guanabara.

Segui os passos indicados no vídeo "Capítulo 19 Aula 01- Download das imagens do capítulo"
Abri o Github Deskstop, cliquei no Show in Explore, abri a pasta de documentos, em seguida, estudos, html-css, exercicios, por fim criei a pasta "ex022".
Abri a pasta "ex022" e criei dentro desta a pasta 'imagens", dentro de imagens inseri as imagens do zip.
Quando subi para o github aparece "ex022/imagens"

Como faço para manter o padrão de deixar o nome da pasta de "ex022" ?

**Comment by DevMarceloCampelo** [comment]
![Repositório Github](https://user-images.githubusercontent.com/106565388/174924556-98092460-a9e9-4935-993f-a4c1179f7731.png)

**Comment by BenjamimCS** [comment]
Tá tudo certo, a pasta `imagens` está sim dentro de `ex022`, isso é um comportamento comum no GitHub, no VSCode também já que é da mesma empresa, não sei se noto isso também.
O que acontece é que quando há apenas uma pasta inserida em um diretório é mostrado junto, mas na verdade o que ele tá mostrando é que a pasta `ex022` contém uma pasta chamada `imagens`.
> A barra (`/`) indica que o que vem antes é uma pasta e o que vem depois é um arquivo ou outra pasta/diretório. Abra o Explorador de Arquivos e você verá isso na "URL" dele umas barra, só que do outro lado (`\`), é só uma peculiaridade do Windows - *por isso não se pode por certos caracteres em nomes de arquivos* ;).

Espero ter ajudado. Se resolveu, feche a Issue, tem uma galera deixando Issue resolvida em aberto.

**Comment by DevMarceloCampelo** [comment]
Obrigado [BenjamimCS](https://github.com/BenjamimCS)
