### ISSUE TITLE
Não encontro os arquivos citados no curso de CSS e HTML 

### ISSUE THREAD

**Issue by filipeoliveirapy** [gustavoguanabara/html-css#255]
Fala @gustavoguanabara , tudo bem meu amigo?
Estou na quinta aula do curso de HTML e CSS no site do [Curso em Vídeos - HTML E CSS](https://www.cursoemvideo.com/curso/html5/) e você cita uns arquivos para baixar através do conteúdo do curso ou através do link na descrição do vídeos do [Canal do Guanabra- aula 5](https://www.youtube.com/watch?v=EANOXuQsglo) para montagem do site durante o decorrer das aulas. Toda via, os arquivos de áudio, css, imagens e etc... não existem, estando disponíveis apenas os arquivos abaixo, o que me impede de dar andamento no curso.

![Sem título](https://user-images.githubusercontent.com/108720194/178855410-d6b7ce55-9989-4bdc-a6c0-71fe385936c6.png)
**ARQUIVOS DESCOMPACTADOS DO DROPBOX NO SITE**

*Obs.: issues montada com conhecimentos adquirido no [CURSO DE GIT E GITHUB](https://www.cursoemvideo.com/curso/curso-de-git-e-github/) no site do [Curso em Víde](https://www.cursoemvideo.com/)*

**Comment by BenjamimCS** [comment]
Na verdade há dois pacotes para você baixar; você pulou o primeiro e baixou somente o segundo. Nesse arquivo dentro de alguma dessas pastas contém arquivos de áudio e vídeo na verdade, e as imagens etc. estão no outro.

**Comment by filipeoliveirapy** [comment]
@BenjamimCS Eu só vi depois que existe um curso mais atual fora do Estudonalta, vou inicar nele e deixar o curso antigo pra la. de qualquer forma, obrigado meu amigo!!

**Comment by BenjamimCS** [comment]
> @BenjamimCS Eu só vi depois que existe um curso mais atual fora do Estudonalta, vou inicar nele e deixar o curso antigo pra la. de qualquer forma, obrigado meu amigo!!

Nahora meu caro.
Recomendo esse novo. Tem muita coisa que será citado nesse curso que evoluíram muito.

Bons estudos ;)
