### ISSUE TITLE
Problema para colocar mostrar o site através do GitHub

### ISSUE THREAD

**Issue by CarlosHenriqueLopes** [gustavoguanabara/html-css#256]
Quando faço a pagina do site do projeto Android, ele aparece sem as definições criadas pelo arquivo CSS, por algum motivo ele mostra tudo, menos o que esta no .css criado no vscode.
Já coloquei todo o caminho das pastas quando o arquivo está na pasta, e sem pasta também, mesmo assim não aparece.

(O site está aparecendo sem as edições que estão no arquivo .css)

**Comment by SilasRodrigues19** [comment]
Opa @CarlosHenriqueLopes, tranquilo? Vi que você criou o arquivo com o nome de ".css" ou seja, só tem a extensão e não tem o nome do arquivo. Muda o nome do arquivo pra algo como style.css, e no HTML altera o href do link pra style.css tbm

**Comment by BenjamimCS** [comment]
> Opa @CarlosHenriqueLopes, tranquilo? Vi que você criou o arquivo com o nome de ".css" ou seja, só tem a extensão e não tem o nome do arquivo. Muda o nome do arquivo pra algo como style.css, e no HTML altera o href do link pra style.css tbm

Por algum motivo, quando se coloca um arquivo como oculto, ao menos no GitHub Pages eles não são carregados. Fiz isso uma vez com uma pasta e também não rolo.
@CarlosHenriqueLopes o jeito é alterar o nome mesmo.

**Comment by CarlosHenriqueLopes** [comment]
@SilasRodrigues19  @BenjamimCS 

Então... eu troquei o nome do arquivo .css e mesmo assim ele não abre com a formatação do arquivo pela page do github, mais pelo index nas pastas ele abre normal.

Peguem o arquivo projeto_android e abram por uma pasta, e depois por uma page feita pelo github para vocês verem o que pode ta acontecendo se possível

**Comment by BenjamimCS** [comment]
> @SilasRodrigues19 @BenjamimCS
> 
> Então... eu troquei o nome do arquivo .css e mesmo assim ele não abre com a formatação do arquivo pela page do github, mais pelo index nas pastas ele abre normal.
> 
> Peguem o arquivo projeto_android e abram por uma pasta, e depois por uma page feita pelo github para vocês verem o que pode ta acontecendo se possível

Abri aqui o seu repositório e ele tá mostrando um erro no carregamento do GitHub Pages aparentemente, _mas ae enquanto eu tava aqui escrevendo eu entrei pra ver o seu GitHub Pages e tá tudo certo_.

Ele na verdade demora algum tempo para verificar as coisas e tal —  pra você entender melhor é só ver naquela barra superior que mostra o último _commit_ o status do andamento do _deploy_, onde tá aparecendo, no seu caso, um x.

Esse só foi um erro interno suponho mas que não possa afetar as coisas. Tá tudo certo, carregue a página denovo e caso não atualize nada, antes de carregá-la novamente, segura `shift` (Chrome, Opera, Edge) ou `control` (Firefox) e atualize pra limpar o _cache_.

**Comment by CarlosHenriqueLopes** [comment]
@BenjamimCS 

Agora foi de primeira, eu tinha lido que as vezes pode acontecer de demorar um pouco para abrir a page como deveria, mais não estava indo.

Obrigado pela ajuda =)
