### ISSUE TITLE
desafio do site cordel

### ISSUE THREAD

**Issue by CarlosHenriqueLopes** [gustavoguanabara/html-css#257]
Estou com um problema para aparecer as imagens de fundo do site.

(OBS: ele ainda não está terminado, mais a toda a base já está pronta com algumas edições, só falta as imagens que não sei porque não aparecem)

**Comment by SilasRodrigues19** [comment]
Opa, boa noite.

Qual o site? tem link do deploy ou do repositório?

**Comment by SilasRodrigues19** [comment]
Faltou dar um ../ no caminho das imagens

```
section#img1 {
    background-image: url('../imagens/background001.jpg');
}

section#img2 {
    background-image: url('../imagens/background002.jpg');
}
```

O ../ serve pra descer um nível e sair da pasta "estilos" sem o ../ só daria certo se a pasta imagens estivesse dentro da pasta estilos

**Comment by CarlosHenriqueLopes** [comment]
vlw esqueci desse  detalhe rs
