### ISSUE TITLE
Duvida: Button vs Input

### ISSUE THREAD

**Issue by leonarita** [gustavoguanabara/html-css#26]
Olá! Gostaria de saber a diferença entre 'button' e 'input type="submit"' nos formulários.

**Comment by leonarita** [comment]
> Olá! Gostaria de saber a diferença entre e nos formulários.

**Comment by leonarita** [comment]
Desculpe as turbulências, é a primeira vez fazendo uma issue rsrs

**Comment by gabrielcarvalh0** [comment]
Olá @leonarita, a diferença pode variar de programador e seu estilo de usar.
Caso você use button e seu type seja submit, ele será semelhante a um input type submit, no qual fará um envio no formulario. A grande diferença fica na declaração das tags e na área visual.
 * A tag ***`<input>`*** contém um atributo de valor value que é exibido e geralmente não é fechada ou é auto fechada.
Exemplo: `<input type="submit" value="Submit" />`

* A tag ***`<button> `*** tem um conteúdo entre a tag de abertura e fechamento, sendo mais flexível do que a tag tradicional, permitindo, por exemplo, imagens e mais estilos visuais. 
Exemplo: `<button type="submit" name="myButton" value="foo">Click me</button>`

Se você usar o button ***type="button"*** aí sim terá diferença, no qual você poderia até usar um evento de clique do javascript.
A grande vantagem do button é que pode ter HTML dentro enquanto que o input é auto-fechado e o texto que ele mostra é definido no atributo `value`.

Via JavaScript pode interceptar o evento submit no caso de, por exemplo, querer fazer uma validação dos dados inseridos no formulário. O type="button" não faz mais do que ser um botão e acionar eventual código que o JavaScript possa ter para ele.

De uma olhada nesses artigos:  
* Quando usar input type=“button” ou input type=“submit”: [click](https://pt.stackoverflow.com/questions/38718/quando-usar-input-type-button-ou-input-type-submit#:~:text=Se%20pergunta%20a%20diferen%C3%A7a%20entre,tem%20nenhuma%20a%C3%A7%C3%A3o%20por%20defeito.)
* Qual a diferença entre button submit e input submit: [click](https://www.devmedia.com.br/forum/qual-a-diferenca-entre-button-submit-e-input-submit/574174)

**Comment by leonarita** [comment]
Obrigado!
