### ISSUE TITLE
Referente ao "Teste seu conhecimento"

### ISSUE THREAD

**Issue by mcaeld** [gustavoguanabara/html-css#260]
Quando essa área foi feita, ela foi pensada pra ser respondida em um caderno (ou na própria folha, caso você imprima) ou só "pra dar uma olhadinha" e ir pro próximo vídeo/pdf?

**Comment by joaohenrik03** [comment]
Isso vai da dedicação de cada um, creio que é melhor fazer o teste(responder) do que apenas dar uma "olhadinha", isso vai te ajudar bastante para ver se você realmente aprendeu, e caso erre alguma, já sabe o que tem que rever. Caso sua dúvida seja esclarecida considere fechar a Issue, boa sorte no seu Teste de conhecimento!
