### ISSUE TITLE
Problema no capítulo 18

### ISSUE THREAD

**Issue by samuelpbastos** [gustavoguanabara/html-css#267]
Olá. 
Eu consegui hospedar o site que crie, porém a URL não abre, fala que deuu erro. Aparece aquele "404 error...".

**Comment by BenjamimCS** [comment]
Olá.
Creio que seu problema já tenha sido discutido aqui, muito provável ser o mesmo da Issue #204. Recomendo dá uma olhada e se for isso mesmo, feche essa Issue, ela já foi resolvida anteriormente.

**Comment by samuelpbastos** [comment]
Verdade. É isso mesmo. Muito obrigado.

**Comment by samuelpbastos** [comment]
Deu certo,  muito obrigado.
