### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by IvanFerroSoares** [gustavoguanabara/html-css#268]
Não consegui publicar meu repositório do local para o remoto. Quando clico no gitHub desktop para publicar ele não consegue me direcionar.
Vi na internet muitos estão com esse problema, nenhuma das soluções apontadas deu certo aqui.
Alguém poderia me socorre por favor?

**Comment by BenjamimCS** [comment]
Olá.
Teria algum print do erro? Você mudou em algm momento o nome do seu repositório remoto ou da branch?

**Comment by IvanFerroSoares** [comment]
Oi...então não mudei o nome não...esse seria o meu primeiro acesso, e o desktop não consegue se conectar como remoto, segue o print:
![Erro github desktop](https://user-images.githubusercontent.com/110257799/182168471-d4a8d822-1168-4507-9a7e-8052dd966b38.png)

**Comment by BenjamimCS** [comment]
Você já vez o que ele manda e se logo pelo navegador? Ou esse erro persiste mesmo assim? Parece ser alguma medida de segurança.

**Comment by IvanFerroSoares** [comment]
Fiz sim... Suspeito que possa ser medida de segurança mesmo, como estou na empresa em que trabalho. O Firewall deve está bloqueando esse dominio.

**Comment by IvanFerroSoares** [comment]
o desktop nem consegue logar na minha conta do gitHub remoto

**Comment by BenjamimCS** [comment]
> Fiz sim... Suspeito que possa ser medida de segurança mesmo, como estou na empresa em que trabalho. O Firewall deve está bloqueando esse dominio.

Queria perguntar isso, li uma Issue se referindo com esse exato problema. Poderia falar com a empresa caso seja possível.

Infelizmente nesse quesito não há muito no que eu possa ajudar, não sei se um proxy ou  vpn acertaria isso.

Poderja ser algo ao antivírus caso use outro.

No caso eu li essa Issue aqui desktop/desktop/issues#11346 do repositório do GitHub Pages.

Espero poder ajudar.

**Comment by IvanFerroSoares** [comment]
Obrigado! vou tentar em casa e se conseguir, então peço liberação aqui na TI da empresa

**Comment by BenjamimCS** [comment]
> Obrigado! vou tentar em casa e se conseguir, então peço liberação aqui na TI da empresa

Caso tenha conseguido, dê um retorno com a solução e feche a Issue, por favor.

**Comment by IvanFerroSoares** [comment]
Não consegui, mas vou fechar assim mesmo obrigado!

**Comment by BenjamimCS** [comment]
> Não consegui, mas vou fechar assim mesmo obrigado!

Poxa...
Pode mantê-la em aberto e dá um título mais explicativo a Issue para melhorar na indexação. Recomendo também que pergunte no [StackOverflow](https://stackoverflow.com) esclarecendo já todos esses detalhes já vistos.
Boa sorte.
