### ISSUE TITLE
zerando margin e padding com *{} , porem o body continua com margin

### ISSUE THREAD

**Issue by rsosilva** [gustavoguanabara/html-css#269]
neste desafio, meu programa continuou com barra de rolagem, que por acaso não gostei, quis tirar as barras e fui inspecionar o index.html.
Comecei diminuindo a porcentagem de enchimento da tela para 99, 98, 97 , e não resolvia. só entao que percebi que mesmo zerando margem e padding no css com *{....} o body continuava com uma margem de 8px que gerava as barras de rolagem na tela.. foi só zerar que o problema foi resolvido.

**Minha questão é: resolvi, mas não entendi... alguém pode me explicar por favor.**

segue trecho do código:
* {
    margin: 0px;
    padding: 0px;
    font-family: Arial, Helvetica, sans-serif;
}

html, body{
    height: 100vh;
    width: 100vw;
    background-color: black;
}

body{
    margin: 0px;  /* **linha acrescentada que resolveu a situação de rolagem de tela***/
    background: url('../imagens/fundo-madeira.jpg') no-repeat top center;
    background-size: cover;
    background-attachment: fixed;
}

**Comment by BenjamimCS** [comment]
Com esse pedaço de código pesquisando me fez achar que fosse algum erro na hora das requisições de estilo favicon etc. no header mas simplesmente não fez sentido. Mas fuçando seu repositório notei que falta um `;` no final da regra do `@charset` do seu arquivo CSS fazendo a próxima regra/bloco ser ignorada pelo parser.

**Comment by rsosilva** [comment]
Realmente ajudou, a falta de ; no charset fez toda a diferença.

**Comment by BenjamimCS** [comment]
> Realmente ajudou, a falta de ; no charset fez toda a diferença.
> 

Se solucionou seu problema, considere-a encerrada; então, por favor, feche a Issue.

**Comment by rsosilva** [comment]
closed
