### ISSUE TITLE
Erro 404 site no github

### ISSUE THREAD

**Issue by Cristiano83dorneles** [gustavoguanabara/html-css#274]
Olá, 
Estou enfrentando dificuldades com a publicação do site no github. 
O primeiro projeto publicou conforme as intruções do guanabara. Porém o projeto cordel e redes sociais, não estou conseguindo publicar. Até gera o link em pages mas dá erro 404 quando abre o site.
Se alguém puder me auxiliar ficarei grato.

**Comment by BenjamimCS** [comment]
Issue #204

**Comment by Cristiano83dorneles** [comment]
Pesquisei esta questão mas não me ajudou. Creio que minha questão seja outra. A princípio, o endereço onde salvei meus trabalhos está correto. Se puder analisar, por gentileza.

https://github.com/Cristiano83dorneles/meus-estudos-html-css/blob/68dea58b47601ebc1797f49bcdef46a651af37e5/erros/erro-acesso-site.png

https://github.com/Cristiano83dorneles/meus-estudos-html-css/blob/67d7669810ac210e2210d08384acab1353ae8fae/erros/print-git-desktop.png

**Comment by BenjamimCS** [comment]
Renomeie assim como fez no [social](https://github.com/Cristiano83dorneles/projeto-social), no repositório do [cordel](https://github.com/Cristiano83dorneles/projeto-cordel-moderno)  tá `cordel.html.html`, o serdor vai procurar sempre por arquivos index com `.html`, `.htm`, `.php` e enfim, renomeie este arquivo para `index.html` somente.

**Comment by Cristiano83dorneles** [comment]
Fiz a alteração mas não funcionou. No caso do projeto-social, o caminho era index e quando alterei para /projeto-social/index.html.html ele abriu o site.
Foi a mesma coisa que tentei no projeto cordel mas não deu certo. Mesmo voltando com a config. anterior

**Comment by BenjamimCS** [comment]
> o servidor vai procurar sempre por arquivos index com .html, .htm, .php

Coloque o arquivo que servirá para a entrada do site como `index.html`, aquivos index eu me referi a `index.html`, `index.htm` etc.

**Comment by Cristiano83dorneles** [comment]
Realmente o problema estava em nomear o .html como index. Agora publicou!
Muito obrigado pela sua disposição!!!

**Comment by BenjamimCS** [comment]
> Realmente o problema estava em nomear o .html como index. Agora publicou! Muito obrigado pela sua disposição!!!

Fico feliz em ajudar.

Mas só deixando claro que já estava tudo publicado, ele só não tinha encontrado um arquivo padrão (index.html e tal), por isso mencionei isso:
> Se você colocar exatamente o atual nome do arquivo na URL ele vai aparecer normalmente o que diz que tá tudo certo como aparenta pelas imagens.

É como se estivesse navegando entre pasta só que pela URL. Meu ponto aqui é só que não confundemos as bolas, hehe, essa Issue deva ter parecido confusa de início, recomendo revê-la.

Se a Issue está resolvida, feche-a, por favor.
Obrigado, bons estudos!📚

**Comment by AiltonCh** [comment]
Boa noite, vi toda a sua explicação sobre a hospedagem, no meu caso eu consegui hospedar o site, porém ele veio somente com o HTML as CSS não vieram, sabe me dizer o por que  ??

**Comment by ErikBarroso** [comment]
O meu só deu certo assim: a sessão "pages" está ao lado esquerdo. Não tem opção de escolher tema. Muda  deixa em none > para main > Root e Deploy from a branch. O pulo do gato, foi que tive que renomear meu arquivo apenas para index tireo o .html. Porque lá no repositório remoto, tava mostrando assim index.html.html. . Então tirei o .html do repositório local, fiz o commit e rodou de boa.
