### ISSUE TITLE
Instalação do GitHub Desktop

### ISSUE THREAD

**Issue by AlessandroEBS** [gustavoguanabara/html-css#276]
Eu instalei o GitHub Desktop, mas quando eu tento executar, aparece uma mensagem de erro. Verifiquei o Sistema Operacional do meu computador e é de 64 bits. Alguém pode me ajudar nisso?
![erro de execução do GitHub Desktop](https://user-images.githubusercontent.com/109595705/183250789-54ca5fab-fa9d-4732-9d43-ebfd9617f84f.JPG)

**Comment by BenjamimCS** [comment]
Assim como dito na Issue https://github.com/gustavoguanabara/html-css/issues/242#issuecomment-1155990083 [^1], essa Issue não teria tanta relação ao curso sendo que você poderia usar outro versionador e enfim (mas use GIT, **ele é superior**). Por ser um passo crucial a aprendizagem acho que isso já possa ajudar (Mas o https://github.com/gustavoguanabara/html-css/issues/242#issuecomment-1155990083 é ainda mais crucial):

Recomendo que verifique se já tem instalado algum dos programas Visual C++ Redistribuitable.
Instale a atualização [KB3063858](https://www.microsoft.com/en-us/download/details.aspx?id=47442) (para x64 segundo você) para o seu Windows e o [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-in/download/details.aspx?id=48145).

Veja se funciona, caso não, refira para https://github.com/gustavoguanabara/html-css/issues/242#issuecomment-1155990083.

> **DISCLAIMER**: essa é uma solução baseada em algumas pesquisas (que poderiam ser feitas por você) com base neste vídeo https://youtu.be/MVmY4JuP7ew. Então não garanto qualquer sucesso, essa foi uma forma de ajudar.

Sucesso, bons estudos! E feche a Issue caso solucione-a e indique a solução para os demais.

[^1]: Para mais instruções de solução de qualquer problema.
