### ISSUE TITLE
Desculpe, você não tem permissão para prosseguir

### ISSUE THREAD

**Issue by kauasilvandrade** [gustavoguanabara/html-css#279]
Esta aparecendo esse erro quando eu prossigo da aula "Configurando iframes"

**Comment by damascenoalex** [comment]
Olá! No Capítulo 22 Aula 2 – Configurando iframes,
ao clicar para marcar como concluído, aparece a seguinte mensagem:
	
Desculpe, você não tem permissão para prosseguir
Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator.

If you believe you should be able to perform this request, please let us know.

RID: ACGZXNFURZQNSVAF6T8WMWUG
