### ISSUE TITLE
github e vs code lentos

### ISSUE THREAD

**Issue by johndgrandson** [gustavoguanabara/html-css#281]
baixei o github desktop no meu pc e ele esta extremamente lento demora bons segundos pra clicar em qq coisa, como se ele ficasse toso travado, não so isso mas desde q instalei ele meu vs code tambem ficou lento oq torna mt chato de praticar, acho estranho até pq meu pc tem ssd e 8g de ram, alguem sabe oq pode ser

**Comment by BenjamimCS** [comment]
Olá.
Você está usando algum antivírus? Veja no Gerenciador de Tarefas se está tudo ok também.

Assim como algumas outras Issues, essas plataformas são a parte, então aqui não seria o melhor lugar a se resolver. Pra uma melhor solução, [pesquise mais sobre](https://github.com/gustavoguanabara/html-css/issues/242#issuecomment-1155990083).
