### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by jose-sindeaux** [gustavoguanabara/html-css#282]
Olá, Professor Guanabara!!! Estou adorando o curso até então, só estou com dúvida sobre aonde está o material do capítulo 21 e 22 (do módulo 4). Acabo por utilizar o material para fazer minhas anotações no caderno. Desde já, grato pela sua atenção :D

**Comment by BenjamimCS** [comment]
Cara, infelizmente tamo tendo essa demora. Ele também tem [outro repositório](https://github.com/professorguanabara/html-css) mas os materiais como os PDFs após o projeto cordel ainda não foram disponibilizados.

**Comment by jose-sindeaux** [comment]
> Cara, infelizmente tamo tendo essa demora. Ele também tem [outro repositório](https://github.com/professorguanabara/html-css) mas os materiais como os PDFs após o projeto cordel ainda não foram disponibilizados.

Beleza, mano!!! Valeu pelo aviso!!!

**Comment by BenjamimCS** [comment]
Boas novas! A Issue #357 há uma solução.
