### ISSUE TITLE
O curso vai ter certificado?

### ISSUE THREAD

**Issue by pedrohenriquebraga** [gustavoguanabara/html-css#29]
Quando o curso acabar, será possível retirar o certificado?

**Comment by rafaelcf13** [comment]
> Quando o curso acabar, será possível retirar o certificado?

Se você estiver fazendo pela plataforma cursoemvideo.com sim, tem o teste e se aprovado o certificado!

**Comment by pedrohenriquebraga** [comment]
Será que do curso atualizado de 2020 também vai ter? @rafaelcf13

**Comment by RuanCarreiroGomes** [comment]
terá sim @pedrohenriquebraga

**Comment by Rodrigojw2014** [comment]
@pedrohenriquebraga Vai ter sim, ele falou isso nos vídeos de estreia do curso pelo You Tube. Basta acessar a playlist para conferir: https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n. Favor fechar sua Issue. Grato!

**Comment by pedrohenriquebraga** [comment]
> @pedrohenriquebraga Vai ter sim, ele falou isso nos vídeos de estreia do curso pelo You Tube. Basta acessar a playlist para conferir: https://www.youtube.com/playlist?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n. Favor fechar sua Issue. Grato!

Obrigado pela resposta!!
Fecharei a Issue. E obrigado a todos que responderam!
