### ISSUE TITLE
Dificuldades com o Módulo 3 de HTML5 e CSS3 Capítulo 21 Aula 12

### ISSUE THREAD

**Issue by silvamariaeduarda** [gustavoguanabara/html-css#291]
**Módulo 3 de HTML5 e CSS3
Capítulo 21 Aula 12 - Desafios (Parte 2)**

Estou tendo problemas para criar uma tabela, não estou conseguindo por a "Nota 1" e "Nota 2" de baixo de notas.

Os códigos da minha tabela:
https://github.com/silvamariaeduarda/html-css/blob/main/desafios/d014/index.html

Minha tabela:
https://silvamariaeduarda.github.io/html-css/desafios/d014/index.html

Esse é o problema que estou relatando, caso tenha mais algo de errado fico contente que pontue!

**Comment by BenjamimCS** [comment]
Pra conseguir esse resultado você teria que usar duas `<tr>` no seu `<thead>` pra poder incluí-las abaixo.

**Comment by AlexCMoreira10** [comment]
@silvamariaeduarda Além do que o BenjamimCS citou logo acima de criar uma tag <tr> dentro do seu <thead> você ira precisar adicionar as configurações de parâmetro rowspan="2" em todas as células com exceção da nota em nota será necessário adicionar colspan="2".

**Comment by marcos-rds** [comment]
seu **<thead>** tem que ficar desse jeito:

> <thead>
>             <tr>
>                 <th scope="col" rowspan="2">Área</th>
>                 <th scope="col" rowspan="2">Disciplinas</th>
>                 <th scope="colgroup" colspan="2">Notas</th>
>                 <th scope="col" rowspan="2">Média</th>           
>             </tr>
>             <tr>
>                 <th scope="col">Nota 1</th>
>                 <th scope="col">Nota 2</th>
>             </tr>
>         </thead>

**Comment by BenjamimCS** [comment]
Caso tenha solucionado sua questão, por favor, feche a Issue.

**Comment by silvamariaeduarda** [comment]
Muito obrigada mesmo aos dois! Deu certo! ^^
