### ISSUE TITLE
fontes do google

### ISSUE THREAD

**Issue by GuiRwis** [gustavoguanabara/html-css#293]
gente quando eu tento pegar a fonte e colocar na varialvel, o cursiva/cursive não fuciona
logo a fonte não consigo usar, alguém pode me ajudar ?

**Comment by AlexCMoreira10** [comment]
Eu fui até o seu Repositório https://github.com/GuiRwis/html-css/blob/main/desafios/desafio%2012/style.css e se estiver se referindo a esse exercício em questão existe um erro no seu @import o seu esta **exatamente assim:** @import url('https://fonts.googleapis.com/css2?família=Sriracha&display=swap');  enquanto **o correto** é @import url('https://fonts.googleapis.com/css2?family=Sriracha&display=swap'); . Caso não tenha notado as diferenças no @import pode colocar no Vscode e ir selecionando letra por letra e vai perceber que em um deles tem uma acentuação extra

além disso quando vc cria a variavel --font2: è necessário adicionar tbm a fonte secundaria ou genérica 'cursive ' pois algum dia a API da letra que esta usando pode sair do ar que ficaria parecido com isso:
   --font2:'Passion One', 'cursive';
   --font3:'Sriracha', 'cursive';

**Comment by GuiRwis** [comment]
valeu manoww. consegui resolver
