### ISSUE TITLE
Problemas para criar o tema no GitHub Pages

### ISSUE THREAD

**Issue by TiagooGobbo** [gustavoguanabara/html-css#294]
Olá, boa tarde! 

Estou com dificuldade em criar o tema para poder fazer a url do meu site funcionar, pois na parte de settings não está aparecendo a parte de GitHube Pages e nem a opção "choose theme''. O que devo fazer?

**Comment by BenjamimCS** [comment]
O Github Pages se encontra na aba `Pages` da seção `Code and automation`, lá vai aparecer as opções desejadas.  Dê uma olhada no que diz a [documentaçãp](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch) também.

> Embora o curso seja recente, a interface do Github mudou nesses dois anos. Qualquer coisa, o [Github Docs](https://docs.github.com) tá ae pra ajudar.
> Caso resolva sua questão, por favor, feche a Issue, e dê a dela um título mais descritivo para ajudar outras pessoas com a mesma questão.

**Comment by TiagooGobbo** [comment]
Consegui. Obrigado !
