### ISSUE TITLE
problema no capítulo 18.

### ISSUE THREAD

**Issue by kalebzaki4** [gustavoguanabara/html-css#296]
não consigo colocar o projeto android no ar para poder hospedar gratis.

**Comment by santosvini** [comment]
bom dia

qual o problema?

**Comment by AlexCMoreira10** [comment]
Se for referente ao seu Repositório https://github.com/kalebzaki4/Site 
   Você colocou o arquivo Index da sua pagina dentro de uma pasta a posta HTML, observação não tem problema vc criar outros arquivos HTML dentro de pasta porém o index tem sempre que ficar dentro da pasta principal.

**Comment by BenjamimCS** [comment]
Isso @AlexCMoreira10.Pra ajudar, na Issue #274 acontece o mesmo e até explico o porquê disso apesar de ser meio óbvio mas recomendo e na própria documentação no 3º passo do tópico [Criando seu site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site) já é dito quais os nomes de arquivos ele vai procurar e **somente** na raiz do seu projeto, na pasta principal.

**Comment by marcos-de-santana** [comment]
Problemas no capítulo 18                      Não consegui achar a mesma página do github-pages aparece para mi outras opções diferentes das que aparece no curso, e por isso não consegui fazer.

**Comment by AiltonCh** [comment]
Boa noite, vi toda a sua explicação sobre a hospedagem, no meu caso eu consegui hospedar o site, porém ele veio somente com o HTML as CSS não vieram, sabe me dizer o por que ??

**Comment by BenjamimCS** [comment]
> Boa noite, vi toda a sua explicação sobre a hospedagem, no meu caso eu consegui hospedar o site, porém ele veio somente com o HTML as CSS não vieram, sabe me dizer o por que ??

Algo me diz ser como você indicou seus arquivos. A Issue #197 pode ser o seu caso.

**Comment by kalebzaki4** [comment]
OBRIGADO!!!
