### ISSUE TITLE
Site CursoemVideo

### ISSUE THREAD

**Issue by pfcouto** [gustavoguanabara/html-css#30]
Olá, boa noite. Não consigo entrar no site novo do cursoemvideo, se trocar de browser consigo novamente, mas logo após abrir algumas abas no site aparece o mesmo erro. Já passei do Chrome para o Opera e já estou no Edge, neste momento não tenho mais nenhum e não queria estar a instalar para continuar a aceder 😆 . Poderia ajudar?
![image](https://user-images.githubusercontent.com/69256195/89478024-af02b080-d786-11ea-88e6-171c93ce90de.png)

**Comment by itsGabrielCruz** [comment]
Oi @pfcouto, o site do Curso em Vídeo teve umas instabilidades ontem. Ficou fora do ar por um bom tempo. Talvez estejam passando por algum problema com o servidor. No momento que estou comentando aqui, tudo segue normal lá.

**Comment by pfcouto** [comment]
@itsGabrielCruz voltei hoje a tentar iniciar o site através do Chrome e do Opera e não consegui novamente. Tentei entrar pelo Edge e deu (parece ser um problema nos browsers, porque antes conseguia entrar normalmente pelo Chrome/Opera, mas agora não), realmente não estou a entender o problema, mas espero que seja resolvido, mesmo que seja um problema do meu lado. Se tiver mais alguma informação peço que informe. Obrigado.

**Comment by pfcouto** [comment]
Limpei os Cookies do site e agora está a funcionar, mas estou com medo que volte a acontecer, era chato se tivesse que estar a fazer todos os dias isto.Não vou fechar o issue porque talvez receba uma resposta melhor. Obrigado pela ajuda @itsGabrielCruz

**Comment by itsGabrielCruz** [comment]
Que bom que conseguiu resolver, @pfcouto. Caso o problema persista, recomendo continuar as suas aulas através das playlists do Youtube no canal do Curso em Vídeo. Então, quando o site voltar você atualiza seu progresso para que consiga concluir seu curso e obter o certificado.

**Comment by pfcouto** [comment]
Olá novamente @itsGabrielCruz eu acompanho sempre pelo YouTube, apenas uso o site para saber quais os cursos que já fiz. Em relação ao certificado é impossível pois sou de Portugal, então não dá para receber. Obrigado.
