### ISSUE TITLE
problemas no capitulo 18 aula 06 "Hospedando site gratuitamente com GitHub Pages"

### ISSUE THREAD

**Issue by emersonsssouza** [gustavoguanabara/html-css#311]
neste cápitulo e aulas percebi que a página  do github foi atualizada e não mostra as mesmas opçoes do site do curso em video e mesmo pesquisando no google em outros sites não achei uma solução para o meu problema, o problema em si está na página github pages onde não aparece a opção de chose a theme

**Comment by LuizCarlos98** [comment]
Boa noite, por o vídeo já fazer um tempinho a configuração pra fazer isso ta diferente. Settings > Pages  > Brach (coloca como main / root > save. Demora uns 5 minutos para o link aparecer!

**Comment by giordanii** [comment]
Como o @LuizCarlos98 citou, você pode selecionar o Github Pages no menu do lado esquerdo da tela:
Code and automation > Pages

**Comment by ThayNyan** [comment]
Como o Luiz disse, demora alguns segundos ou minutos pro github disponibilizar o seu link la em cima, depois que abrir o link da pagina você pode verificar se o nome do arquivo que vc renomeou está como index.html.html, eu passei 3 dias pra descobri que era isso que tava dando erro 404 no meu. então no final ele vai te da o https://aluno.github.io/android-projeto/ ai você adiciona o **index.html** no final ou **index.html.html** só pra testar se pode ser isso. Se for vc ajusta no pc passa pro repositorio e comita pra corrigir.

**Comment by emersonsssouza** [comment]
Boa noite pessoal, quero agradecer a vocês todos que contribuíram @ThayNyan  @giordanii  @LuizCarlos98  por me ajudarem nisso tentei por alguns dias até que finalmente hoje consegui colocar o github pages funcionar o link demorava mais do que o normal para aparecer para mim e a configuração também estava um tanto diferente, mas no fim deu tudo certo meus links já estão funcionando mais uma vez meu muito obrigado e bons estudos para vocês!

**Comment by ErikBarroso** [comment]
O meu só deu certo assim: a sessão "pages" está ao lado esquerdo. Não tem opção de escolher tema. Muda  deixa em none > para main > Root e Deploy from a branch. O pulo do gato, foi que tive que renomear meu arquivo apenas para index tireo o .html. Porque lá no repositório remoto, tava mostrando assim index.html.html. . Então tirei o .html do repositório local, fiz o commit e rodou de boa.
