### ISSUE TITLE
Problema do desafio 012

### ISSUE THREAD

**Issue by Nathan-Rodrigues0** [gustavoguanabara/html-css#318]
estou com github desktop clonado, faço o código base e eu abro o arquivo HTML e na página não aparece nada, e esta informando que esta com 0 bytes, qual é a solução ou problema?

**Comment by BenjamimCS** [comment]
Pode parecer besta, mas você salvou o arquivo? Editar e arquivo vazio essa me parece a única opção.
Poderia ser mais claro? Por favor.

**Comment by Nathan-Rodrigues0** [comment]
qual arquivo? já dei commit, quando faço o código básico no vscode e depois vou abrir o navegador que esta o arquivo html, ele abre, mas não tem nada, mesmo eu alterando no vscode
Automaticamente quando voce abre um arquivo html em um navegador mesmo sem nada na página, ele altera no bytes, no meu caso mesmo eu ja tendo colocando um texto, ele continua contando que esta sem conteúdo na página, 0 bytes

**Comment by Nathan-Rodrigues0** [comment]
Obrigado pela atenção! já consegui resolver, era apenas um bug mesmo.
