### ISSUE TITLE
Materiais em PDF do módulo 4 do curso de HTML5 e CSS3

### ISSUE THREAD

**Issue by SuzaneDoccy** [gustavoguanabara/html-css#324]
Olá, professor, estou fazendo o curso de HTML5 e CSS3, já estou no módulo 4. Não estou encontrando os materiais em PDF desse módulo, somente do módulo 3 pra trás, na parte dos materiais no repositório do Github e já tem muito tempo que o conteúdo foi publicado e já tem algumas semanas que espero aparecer e nada. Pode me ajudar? Estou fazendo anotações no caderno usando o material de apoio e as aulas.

**Comment by Dan-Coelho** [comment]
Gostaria de reforçar a mensagem anterior sobre a falta dos PDFs e acrescentar que o curso (na plataforma cursoemvideo.com) está faltando algumas aulas e o teste

**Comment by kalebzaki4** [comment]
pode ser que ele não adicionou ainda, mesmo tendo lançado os videos e os conteudos.

**Comment by BenjamimCS** [comment]
Issue #310

**Comment by SuzaneDoccy** [comment]
> Issue #310

Caramba ... Teve outros comments antes de mim... Não tinha visto. Que coisa estranha. Obrigada por me mostrar. Tomara que vejam logo e nos ajudem, tem outra forma de entrar em contato pra me responderem

**Comment by BenjamimCS** [comment]
> > Issue #310
> 
> Caramba ... Teve outros comments antes de mim... Não tinha visto. Que coisa estranha. Obrigada por me mostrar. Tomara que vejam logo e nos ajudem, tem outra forma de entrar em contato pra me responderem 

> É bom checar outras Issues antes pra não duplicar como já tá acontecendo. Vamo linka-las pros outros pra reduzir isso.

Bem apontado sobre o Guanabara ter uma equipe: acho que o único modo de conseguir contato seria no Instagram do Curso em Vídeo. Seria uma boa já que por aqui tá somente nós alunos se ajudando.

**Comment by SuzaneDoccy** [comment]
> > > Issue #310
> > 
> > 
> > Caramba ... Teve outros comments antes de mim... Não tinha visto. Que coisa estranha. Obrigada por me mostrar. Tomara que vejam logo e nos ajudem, tem outra forma de entrar em contato pra me responderem
> 
> > É bom checar outras Issues antes pra não duplicar como já tá acontecendo em outras. **Vamo linka-las pros outros pra reduzir isso.**
> 
> Bem apontado sobre o Guanabara ter uma equipe: acho que o único modo de conseguir contato seria no Instagram do Curso em Vídeo. Seria uma boa já que por aqui tá somente nós alunos se ajudando.

Ta bom, muito obrigada. Irei entrar em contato pelo insta

**Comment by artur-ferreira-dev** [comment]
Boa noite pessoal, recebi uma resposta do Curso em Vídeo então o jeito é esperar segue a mensagem:
Olá Pequeno Gafanhoto, 
 
Agradecemos o seu contato. 
 
Informamos que o módulo 4 não esta completo na plataforma, breve novas aulas e material serão inseridos.
 
Atenciosamente, 
Equipe Curso em Vídeo

**Comment by Leal86** [comment]
> Boa noite pessoal, recebi uma resposta do Curso em Vídeo então o jeito é esperar segue a mensagem: Olá Pequeno Gafanhoto,
> 
> Agradecemos o seu contato.
> 
> Informamos que o módulo 4 não esta completo na plataforma, breve novas aulas e material serão inseridos.
> 
> Atenciosamente, Equipe Curso em Vídeo



Bom dia a todos, recebi a mesma mensagem a dois dias atrás, o professor deve estar super enrolado com muito trabalho rsrs...

Brincadeiras à parte espero que ele possa subir os materiais o quanto antes

**Comment by SuzaneDoccy** [comment]
> > Boa noite pessoal, recebi uma resposta do Curso em Vídeo então o jeito é esperar segue a mensagem: Olá Pequeno Gafanhoto,
> > Agradecemos o seu contato.
> > Informamos que o módulo 4 não esta completo na plataforma, breve novas aulas e material serão inseridos.
> > Atenciosamente, Equipe Curso em Vídeo
> 
> Bom dia a todos, recebi a mesma mensagem a dois dias atrás, o professor deve estar super enrolado com muito trabalho rsrs...
> 
> Brincadeiras à parte espero que ele possa subir os materiais o quanto antes

Eu acredito que ele esteja criando outros projetos e dando seguimento a outros cursos, por exemplo ele iniciou um curso a algumas semanas sobre segurança se não me engano, mas o que é estranho é ele não ter feito materiais na ordem em que foi concluindo os módulos anteriores.... Já que antes eram 3 aulas por semana se não me engano e já faz um ano que o capítulo 20 foi publicado no repositório. E me pergunto se para os que pagam aquele plano no Curso em Vídeo também estão sem materiais, será que eles recebem os conteúdos em PDF também pelo github?
Porque pra quem paga o negócio lá recebe o conteúdo antes de todo mundo com todas as aulas pelo o que eu entendi, então de qualquer forma não é ele quem posta no you tube, nem atualiza os repositórios e nem atualiza os vídeos no site do Curso em Vídeo

**Comment by Leal86** [comment]
> > > Boa noite pessoal, recebi uma resposta do Curso em Vídeo então o jeito é esperar segue a mensagem: Olá Pequeno Gafanhoto,
> > > Agradecemos o seu contato.
> > > Informamos que o módulo 4 não esta completo na plataforma, breve novas aulas e material serão inseridos.
> > > Atenciosamente, Equipe Curso em Vídeo
> > 
> > 
> > Bom dia a todos, recebi a mesma mensagem a dois dias atrás, o professor deve estar super enrolado com muito trabalho rsrs...
> > Brincadeiras à parte espero que ele possa subir os materiais o quanto antes
> 
> Eu acredito que ele esteja criando outros projetos e dando seguimento a outros cursos, por exemplo ele iniciou um curso a algumas semanas sobre segurança se não me engano, mas o que é estranho é ele não ter feito materiais na ordem em que foi concluindo os módulos anteriores.... Já que antes eram 3 aulas por semana se não me engano e já faz um ano que o capítulo 20 foi publicado no repositório. E me pergunto se para os que pagam aquele plano no Curso em Vídeo também estão sem materiais, será que eles recebem os conteúdos em PDF também pelo github? Porque pra quem paga o negócio lá recebe o conteúdo antes de todo mundo com todas as aulas pelo o que eu entendi, então de qualquer forma não é ele quem posta no you tube, nem atualiza os repositórios e nem atualiza os vídeos no site do Curso em Vídeo

Então @SuzaneDoccy eu sou apoiador e mesmo assim não recebi nem foram disponibilizados os materiais em pdf em nenhum lugar (pelo menos que eu saiba, ne?! rsrs...) , a única coisa que aconteceu nesse 4º módulo é que as aulas ficaram disponíveis mais rápido pq quando comecei a ser apoiador os outros já estavam completos.

**Comment by MarceloCarvalhoRJ** [comment]
Boa noite a todos! Sou apoiador do curso em video e não tem o material do modulo 4. O Github é o mesmo para todos.

**Comment by cosmodej** [comment]
é uma pena qe o gustavo guanabara não ver esses comentarios porque seria muito importante esses pdfs e ele fala que tem esses pdfs só não sabemos onde esta

**Comment by BenjamimCS** [comment]
Na Issue #357 há uma solução! Feche esta Issue em prol de manter somente a #357.

**Comment by wallaceaquino** [comment]
Sei que já faz um bom tempo que postaram essas mensagens aqui. É que estou na mesma questão, não encontro os capítulo após o 20, nem mesmo os exercícios após o 23. O meu caso é um pouco pior, pois sou cego e estava me apoiando totalmente nos pdf e nos códigos dos exercícios.

**Comment by BenjamimCS** [comment]
@wallaceaquino na Issue que eu mencionei anteriormente fala mais sobre o assunto desses pdfs mas vou deixar aqui o link dos deles (o 23 não está presente por algun motivo). [Aqui você acessar os pdfs](https://github.com/gustavoguanabara/html-css/tree/fe6653ecdafa5b7275a5ecb4c36a8ca14f5043e7/aulas-pdf).

Novamente, para entender melhor tem a Issue #357.

**Comment by MihCarvalho82** [comment]
Grata @BenjamimCS , pra quem chegar aqui em 2026 os pdfs ainda podem ser encontrados.
