### ISSUE TITLE
Imagens do módulo 3 ex22

### ISSUE THREAD

**Issue by Mathsmano** [gustavoguanabara/html-css#326]
Pessoal ja rodei pelos repositórios do Guanabara(html5/css3)e não acho as fotos para dowload,e muito menos o próprio exercício,alguem pode me ajudar?

**Comment by kalebzaki4** [comment]
ele não tinha adicionado o exercicio tempo atras, ou pode ter acontecido um bug, mas nesse exercicio não havia imagens.

**Comment by BenjamimCS** [comment]
Issue #320

**Comment by Mathsmano** [comment]
Então,achei o repositório (html/css),apertei em navegar pelo código e achei o exercício 22,as imagens e etc,porém não aparece a opção de dowload.

**Comment by BenjamimCS** [comment]
> Então,achei o repositório (html/css),apertei em navegar pelo código e achei o exercício 22,as imagens e etc,porém não aparece a opção de dowload.

Na verdade, essas imagens estão neste repositório em `exercicios/modulo-03/ex022` num zip. Erro meu, desculpa. Achei que esse exercício não estava aqui e somente no outro repositório.

**Comment by Mathsmano** [comment]
- [ ] Obrigado,estão num arquivo zip,Ja fiz o dowload agora posso progredir com a aula.
