### ISSUE TITLE
Tabela desafio02 do Capítulo 21 - Aula 12 - Problema ao aplicar estilo em caption

### ISSUE THREAD

**Issue by luanstefano** [gustavoguanabara/html-css#329]
Ao tentar aplicar estilo ao caption da tabela, nada acontece. Segue o exercício:

[Tabela Cap 21 - Aula 12](https://luanstefano.github.io/html-css/exercicios/ex023/tabela007.html
)

[Código](https://github.com/luanstefano/html-css/blob/main/exercicios/ex023/tabela007.html)

Não postei o código diretamente pois achei que ficaria muito extenso, mas se for mais fácil, posto.
A quem puder me esclarecer essa duvida, grato desde já.

**Comment by luanstefano** [comment]
Ja encontrei o problema, eu estava usando da seguinte forma: 

```
<caption></caption>
<table></table>
```

Quando caption devia estar inserido em table. Uma desatenção.

**Comment by BenjamimCS** [comment]
Com a Issue resolvida, por favor, feche-a.
