### ISSUE TITLE
Dúvida básica no desafio 10

### ISSUE THREAD

**Issue by devpedromelo** [gustavoguanabara/html-css#330]
Olá, estou com um probleminha no desafio 10, é um problema pequeno que tá mais pra uma dúvida do que um problema em si.
Acontece quando usei o columns no ul, não funcionou, a ul continua do mesmo jeito...
Alguém pode me dizer se teve o mesmo problema? Ou se tem outra forma mais recente de separar uma lista em duas colunas?

**Comment by VittoBaroni** [comment]
Opa pedro, tudo bem ?

então, eu tive o mesmo problema quando fiz pela primeira vez. O meu erro foi quando eu fiz o código, e tinha esquecido de colocar a tag <li> em cada item quando se coloca a tag. Ve se não é o mesmo problema que o seu, talvez seja

**Comment by devpedromelo** [comment]
Valeeeeu! Acabou que era basicamente isso, eu tinha colocado o <li>, porém a tag <abbr> estava antes do <li>, era isso que estava impossibilitando de dividir as colunas hahaha

**Comment by devpedromelo** [comment]
Valeeeu! Acabou que eu tinha colocado o < li > mas a tag < abbr > estava na frente e era isso que estava impossibilitando de dividir as colunas hahaha

**Comment by RosanaArioza** [comment]
Estou com o mesmo problema, não consigo dividir a lista em 2 colunas . 
Alguma sugestão?
<ol>
                    <li>1.5 - Cupcake</li>
                    <li>1.6 - Donut</li>
                    <li>3.0 - Eclair</li>
                    <li>2.2 - Froyo</li>
                    <li>2.3 - Gingerbread</li>
                    <li>3.0 - Honeycomb</li>
                    <li>4.0 - Ice Cream Sandwich</li>                        
                    <li>4.1 - Jelly Bean</li>
                    <li>4.4 - KitKat</li>
                    <li>5.0 - Lolipop</li>
                    <li>6.0 - Marshmallow</li>
                    <li>7.0 - Nougat</li>
                    <li>8.0 - Oreo</li>
                    <li>9.0 - Pie</li>
                </ol>

**Comment by Karini2037** [comment]
Tenta colocar no CSS assim coluns: 2

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Karini2037** [comment]
Tenta colocar Coluns: 2;

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
