### ISSUE TITLE
Problema mobile com o desafio 10

### ISSUE THREAD

**Issue by deysemartellet** [gustavoguanabara/html-css#332]
Boa noite, gente! Terminei há alguns dias o desafio 10 de projeto Android e coloquei aqui no Github. No navegador do Pc ficou perfeito, porém, no celular ficou com o header, o nav e o footer estranhos. 
![Screenshot_2022-10-26-21-55-37-797_com android chrome](https://user-images.githubusercontent.com/114524231/198166352-23d37c3b-f09e-46d7-acde-18b30547da75.jpg)
![Screenshot_2022-10-26-21-55-43-032_com android chrome](https://user-images.githubusercontent.com/114524231/198166372-7fd06bd6-b883-4fc6-9ed1-1a5099289a29.jpg)
 
Não sei bem como arrumar isso, já que minhas margens estão auto. Alguém teve o mesmo problema ou sabe como me ajudar?

Agradeço desde já!

**Comment by devpedromelo** [comment]
Olá, dá uma conferida na margin ou no padding dos dois... mas acho que o problema está na responsividade, você colocou uma largura minima e máxima no main?

**Comment by devpedromelo** [comment]
dei uma olhada no seu repositório e vi que tem um erro na declaração global la na sua folha de estilo, na declaração global do padding você escreveu opx em vez de 0px.... pode ser por isso que está dando erro!

**Comment by deysemartellet** [comment]
> dei uma olhada no seu repositório e vi que tem um erro na declaração global la na sua folha de estilo, na declaração global do padding você escreveu opx em vez de 0px.... pode ser por isso que está dando erro!

Oi, boa noite. Obrigada pela ajuda, sempre acabo trocando o 0 pelo o sem querer. Porém, mesmo depois de ajeitar isso o projeto no celular não mudou...

**Comment by BenjamimCS** [comment]
O seu `<main>` tá com `min-width` e só tá diminuindo até o tanto definido. De início, pela print, achei que fosse o `footer` e o `header` por alguma regra presente em ambos, mas na verdade foi o inverso, é o que está definido no seu `<main>` e eles tão seguindo o fluxo do seu viewport exceto o `main`.

**PS**: as suas imagens com  a classe `.pequena` tão com um tamanho fixo também, coloque medidas relativas pra evitar esse outro overflow.

**Comment by deysemartellet** [comment]
Você sabe como eu poderia evitar isso no futuro? Por exemplo, eu uso a extensão que o Gustavo passou na aula, o window resizer, só que por ele tava normal. Só que fui testar no meu celular e ficou desse jeito. Já em outra tela ficou com o main todo pra esquerda. Aí fico toda confusa em relação a responsividade se não consigo ver em outros dispositivos...

**Comment by BenjamimCS** [comment]
O Inspecionar traz o Dev Tools que traz muita coisa como uma ferramenta que lhe permite simular e bem o navegador em um dispositivo móvel. Como exemplo, quando fui usar `overflow: hidden` no `<body>` e simplesmente não funcionou quando fui ver pelo celular (é uma peculiaridade nos navegadores mobile, ao menos nos que testei) e a melhor forma de averiguar e contornar isso foi vendo por ele. **Recomendo.**
A opção é essa aqui:

![image](https://user-images.githubusercontent.com/83431838/198312413-292c6fd8-38d5-48e0-9401-e1ddf42941b8.png)

Pesquisando cê acha bons tutoriais dela.

**Comment by deysemartellet** [comment]
Obrigada, gente! Deu tudo certinho aqui! Arrumei o min-width já usando essa ferramenta do Dev Tools. Agradeço muito pela dica!

**Comment by deysemartellet** [comment]
Obrigada, gente! Deu tudo certinho aqui! Arrumei o min-width já usando essa ferramenta do Dev Tools. Agradeço muito pela dica!
