### ISSUE TITLE
Problema ao concluir video aula pela plataforma CursoemVideo.

### ISSUE THREAD

**Issue by luanstefano** [gustavoguanabara/html-css#336]
Estou no módulo 4 do curso de HTML e CSS e pela primeira vez me deparei com o seguinte problema ao terminar uma video aula e clicar para marcar como concluido: 

"Desculpe, você não tem permissão para prosseguir
Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator.

If you believe you should be able to perform this request, please let us know.

RID: HWRNNIU9OFBK7EG51DVOQBMF"

Ja atualizei a pagina e tentei concluir de novo, já fechei e abri novamente.

**Comment by RenatoDeFreitas** [comment]
Veja o vídeo a seguir! 
https://www.youtube.com/watch?v=qLKaN5Q8uBU&t=322s
