### ISSUE TITLE
Problema na aula 18 - Aprendendo Git e GitHub

### ISSUE THREAD

**Issue by 1rueful** [gustavoguanabara/html-css#338]
Só para mim não existe o arquivo .pdf?

**Comment by mauriciolsilva** [comment]
Pra fazer o exercício cordel é isso?
Se for amanhã me chama aqui que te mando o anexo, vou compartilho meu git.

Em ter., 8 de nov. de 2022 23:50, Rafael Brazão ***@***.***>
escreveu:
