### ISSUE TITLE
Projeto-Social

### ISSUE THREAD

**Issue by alvescamila87** [gustavoguanabara/html-css#342]
Olá pessoal!

1. Criei o projeto da rede social no mobile, porém o meu background não esticou para a tela toda tendo realizado as configurações de style exatamente iguais ao vídeo. Conseguem me ajudar?

![image](https://user-images.githubusercontent.com/116912821/201410621-22a0cb57-8424-4899-8c36-1bc2eeffc89d.png)

2. Outro ponto que percebi foi essa margem mesmo que setada as configurações padrões zeradas no style:
![image](https://user-images.githubusercontent.com/116912821/201410934-ff9f8617-1093-4da3-8311-2bb154bdc39e.png)

3. Por último, somente a rede social do Instagram que apresentou esse scroll vertical e horizontal de modo que não ficasse enquadrado como as demais "redes sociais".

![image](https://user-images.githubusercontent.com/116912821/201411137-32ac93d5-27c9-45aa-b87f-09f82d05d29c.png)

**Comment by martinsmatheus-dev** [comment]
Este tópico 3 que você colocou, quanto a configuração do "scroll", pelo que vi no seu html referente ao Instagram... nele você não colocou um "link" para CSS. 
Qualquer coisa crie um 'Style' interno e coloque as configurações -webkit-scrollbar {...}.

Espero ter ajudado.

**Comment by BenjamimCS** [comment]
Preste sempre atenção: o `social.css` tá com erro de sintaxe, aí a regra seguinte (`* {...}`) não funciona; o conteiner onde é declarado o _background_ está com a medida relativa a altura (`vh`). Por isso tais erros em rolagem, margem e tamanhos.

Já dizia o professor: se tivesse feito igual teria funcionado. Olhe seu código, revise, entenda.

Espero ter ajudado. Bons estudos!!📚

**Comment by alvescamila87** [comment]
> Este tópico 3 que você colocou, quanto a configuração do "scroll", pelo que vi no seu html referente ao Instagram... nele você não colocou um "link" para CSS. Qualquer coisa crie um 'Style' interno e coloque as configurações -webkit-scrollbar {...}.
> 
> Espero ter ajudado.

Muito obrigada!!!
Realmente não havia linkado o css "social" à página do de html do instagram.

**Comment by alvescamila87** [comment]
> Preste sempre atenção: o `social.css` tá com erro de sintaxe, aí a regra seguinte (`* {...}`) não funciona; o conteiner onde é declarado o _background_ está com a medida relativa a altura (`vh`). Por isso tais erros em rolagem, margem e tamanhos.
> 
> Já dizia o professor: se tivesse feito igual teria funcionado. Olhe seu código, revise, entenda.
> 
> Espero também ter ajudado. Bons estudos!!📚

Muito obrigada!
Corrigi:
- o erro de sintaxe na regra do CSS social;
- a medida relativa ao height de vh para vw;

**Comment by BenjamimCS** [comment]
Com a Issue encerrada, por favor, feche-a.
