### ISSUE TITLE
capítulo 19 aula 02 ALGUÉM ME AJUDA!!!!

### ISSUE THREAD

**Issue by juliaamarall** [gustavoguanabara/html-css#347]
Não estou encontrando o arquivo ZIP com as imagens que serão utilizadas no modulo.

HELPPPPPPP

**Comment by BenjamimCS** [comment]
Mano... você ao menos deu uma olhada nos arquivos neste repositório?

**Comment by ViniciusYoda** [comment]
procura no outro repositório dele

**Comment by BenjamimCS** [comment]
🤦‍♂️
