### ISSUE TITLE
Error na hora de criar novo ou adicionar repositório no GitHub Desktop - referente ao Cap. 18

### ISSUE THREAD

**Issue by carlos-salvio** [gustavoguanabara/html-css#349]
Tentei por dias resolver ou achar sozinho na rede, mas desisti, se alguém puder me ajudar, ficarei agradecidíssimo.
Obs.: **Github Desktop para Linux**.

Tento adicionar um novo repositório como "Add new repository" como Guanabara ensina no Cap.18. Porém ele não permite pela pasta ser existente:

![Captura de ecrã de 2022-11-23 16-21-51](https://user-images.githubusercontent.com/118013218/203632288-f655d094-676e-42bd-b636-7a9f118060c0.png)

Segundo a legenda, ela já é um repositório, porém nunca havia add antes e todos que eu preencho o nome de acordo com a pasta que quero aparece isso (digo pelo modo ensino pelo professor Guanabara). E o botão "Create Repsitory" fica transparente e inclicável, sem possibilidade de prosseguimento. Daí clicando em "Add this repository" vem o problema consequente.

![Captura de ecrã de 2022-11-23 16-23-02](https://user-images.githubusercontent.com/118013218/203633290-16145e81-8b9c-4f93-83c9-63448490b305.png)

Ele só permite adicionar o caminho até o usuário,

![Captura de ecrã de 2022-11-23 16-24-02](https://user-images.githubusercontent.com/118013218/203633460-b268ec45-7236-42df-8d44-faa6cfa1ee65.png)

E mesmo eu forçando o caminho completo (pelo Choose ou sem ele) como na imagem acima, não funciona. 
Quando clico em "Add repository" ele cria o repositório pelo caminho  *_/home/carlos_*   somente, considerando todos os arquivos do computador pelo usuário _carlos_ ,como na imagem abaixo:

![Captura de ecrã de 2022-11-23 16-24-12](https://user-images.githubusercontent.com/118013218/203633802-67075812-7eae-4d12-b331-d3c51d864ecb.png)

![Captura de ecrã de 2022-11-23 16-24-17](https://user-images.githubusercontent.com/118013218/203633908-446b8385-91fc-4c0b-93f1-d2966455bf44.png)

Já tentei de tudo, fiz e refiz, procurei cada detalhe (e pode ser que seja justamente um que não sei enxergar). Caso alguém saiba ou já tenha passado pela mesma situação, ficarei agradecido demais de receber alguma dica.
 Lembrando que é o **Github Desktop para Linux**.

**Comment by BenjamimCS** [comment]
Então assumindo que o diretório HTML5-CSS3 não seja um repositório Git (não há presença do diretório oculto `.git` nele)  e tendo os passos sido feito corretamente, você já verificou se não há nenhum outro `.git` nos diretórios pai?

Tem uma Issue aqui no GitHub no repositório da ferramenta com um problema muito parecido - se não for o mesmo. Recomendo que dê uma olhada: https://github.com/desktop/desktop/issues/3036

**Comment by carlos-salvio** [comment]
@BenjamimCS Na mosca !!!

Havia um diretório ` .git ` na _Pasta Pessoal_ . Não sei como ela foi parar lá, mas inviabilizava a adição de qualquer repositório desse ponto adiante. Eu havia visto ela, mas não imaginei que fosse um repositório, pensei que seriam arquivos do próprio _Git_ justamente pela localização. Uma vez excluída, pude prosseguir com as atividades normalmente.

Muito obrigado pela ajuda, pela recomendação de issue que me esclareceu e pela atenção.
