### ISSUE TITLE
Problema do d010

### ISSUE THREAD

**Issue by ingrid-vidal** [gustavoguanabara/html-css#354]
Não estou conseguindo arrumar o header, no celular ele não está ocupando toda a largura, mas o resto está tudo certinho e funcionando. Já olhei os c´digos no vídeo para ver se fiz algo errado e estava igual

**Comment by Anando12** [comment]
Successful

OPPO F15

**Comment by devpedromelo** [comment]
Dei uma olhada no seu código, tenta diminuir o "min-height" pra 150px e tira o display block para ver se resolve!

**Comment by ingrid-vidal** [comment]
> Dei uma olhada no seu código, tenta diminuir o "min-height" pra 150px e tira o display block para ver se resolve!

Eu coloquei mas não deu certo e o footer também está com o mesmo problema

**Comment by ingrid-vidal** [comment]
> Dei uma olhada no seu código, tenta diminuir o "min-height" pra 150px e tira o display block para ver se resolve!

Consegui resolver, era uma medida la do main. Mas muito obrigada
