### ISSUE TITLE
Mód. 03 - Fonte "Android" não abre no Mobile

### ISSUE THREAD

**Issue by vIRIATOpill** [gustavoguanabara/html-css#356]
Alguém me ajuda pfvr?

Durante a execução das aulas do Mód. 03 a respeito do Github, estou tendo dificuldades na hora de abrir o site no celular, ao invés de aparecer a fonte "Android" no main > h1 e h2, está aparecendo a fonte cursiva, ja tentei resolver de todas as formas e nada, se alguem puder dar uma dica, fico agradecido.

**Comment by BenjamimCS** [comment]
Provável na forma de como você está indicando a fonte. Coincidentemente, a Issue #355 é bem semelhante. Se for o mesmo, feche-a, por favor.

**Comment by devpedromelo** [comment]
Tenta indicar a fonte manualmente no h1 e no h2, em vez de declará-la em uma variável no CSS pra ver se funciona.

**Comment by BenjamimCS** [comment]
Caso tenha solucionado, por favor, feche a Issue. Senão prossiga, por favor.
