### ISSUE TITLE
Módulo 4 do Curso de HTML e CSS

### ISSUE THREAD

**Issue by gustawantstobattle** [gustavoguanabara/html-css#361]
O módulo 4 de html e css está totalmente vazio, todas as aulas não estão mais lá

**Comment by devpedromelo** [comment]
no site do curso em video?

**Comment by gustawantstobattle** [comment]
sim, mas agora já voltou ao normal.

**Comment by gustawantstobattle** [comment]
sim, mas agora já voltou ao normal
