### ISSUE TITLE
Problemas no capitulo 18

### ISSUE THREAD

**Issue by leohaley** [gustavoguanabara/html-css#364]
Tentei criar minha conta no GitHub e o email não chega!

**Comment by lucaslinyker** [comment]
Olá, sei que você fez essa issue devido ao curso do Gustavo Guanabara, e queria convidar você a fechá-la.

**Comment by BenjamimCS** [comment]
Verifique se é o mesmo endereço, span, email proxy (caso tenha) e enfim. Aqui não seria o melhor lugar a se buscar o que você queira. Por favor, encerre essa Issue. 

O Github Docs pode ajudar.
