### ISSUE TITLE
Capítulo 18 Aula 09

### ISSUE THREAD

**Issue by GustavoFroehlich** [gustavoguanabara/html-css#366]
Eu não estou achando a opção de clonar/baixar código, alguém poderia gentilmente me ajudar?

**Comment by santosvini** [comment]
opa, qual código vc precisa?

**Comment by GustavoFroehlich** [comment]
> opa, qual código vc precisa?

ent cara, eu n preciso do código, eu so quero aprender mesmo onde que fica para baixar caso no futuro eu precise, fora q na aula ele ta ensinando isso, mas onde ele mostra o botão de baixar não tem para mim, e eu gosto de ver a aula e ir acompanhando

**Comment by santosvini** [comment]
> Segue onde está o botão de clone do repo

![image](https://user-images.githubusercontent.com/46813491/209729068-65bb1558-27a7-4db1-b7e3-91bb3be2e801.png)

**Comment by GustavoFroehlich** [comment]
> opa, qual código vc precisa?

ent cara, na vdd eu não preciso de nenhum, so quero aprender mesmo onde fica para clonar/baixar, nessa aula ai que eu coloquei no titiulo ate tem ele ensinando, so q onde ele mostra o botão, não aparece pra mim, e como o curso é menho antigo acho q o Git pode ter atualizado e ter trocado de lugar.

**Comment by GustavoFroehlich** [comment]
> > Segue onde está o botão de clone do repo
> 
> ![image](https://user-images.githubusercontent.com/46813491/209729068-65bb1558-27a7-4db1-b7e3-91bb3be2e801.png)
valeu cara, mt obrigado, me ajudou bastante.

**Comment by santosvini** [comment]
> Não esquece do git clone [link] caso faça via terminal
