### ISSUE TITLE
desafios só vão até o quarto módulo

### ISSUE THREAD

**Issue by broumillac** [gustavoguanabara/html-css#372]
Na aula do capitulo 10 pede para executar os desafios, mas não está disponivel

**Comment by BenjamimCS** [comment]
Esses desafios são do Módulo 1 e estão neste repositório somente os materiais para você usar, são mostrados em vídeo lá certinho. Caso esteja querendo achá-los já resolvidos eu recomendaria fazer você mesmo e qualquer coisa iniciar uma Issue perguntando o seu problema, tamo aqui pra ajudar!

**Comment by broumillac** [comment]
> Esses desafios são do Módulo 1 e estão neste repositório somente os materiais para você usar, são mostrados em vídeo lá certinho. Caso esteja querendo achá-los já resolvidos eu recomendo fazer você mesmo e qualquer coisa iniciar uma Problema doloroso o seu problema, tamo aqui pra ajudar!
> 
> > **PS:** sendo essa a solução, feche a Issue, por favor.

Estou no módulo 1. No capítulo 10 pede para fazer os desafios 5 e 6. Não consigo achar aqui no link disponibilizado. Coma faço ? 
Agora no capitulo 11 foi pedido para fazer o desafio 9

**Comment by BenjamimCS** [comment]
@broumillac 
> Estou no módulo 1. No capítulo 10 pede para fazer os desafios 5 e 6. Não consigo achar aqui no link disponibilizado. Coma faço ? Agora no capitulo 11 foi pedido para fazer o desafio 9

Estão todos neste repositório. Na aba [`Code`](/gustavoguanabara/html-css) contém as pastas com quase todo o conteúdo. Os desafios, como você mesmo disse, estão aqui até o Módulo 4. Eles estão aqui, certo? Como ele mostra em vídeo, tem os PDF e materiais como já lhe disse.

**Comment by broumillac** [comment]
@BenjamimCS  pelo link que você mencionou consegui acessar, eu não estava conseguindo acessar antes não sei pq. so abria até o quarto desafio. Muito Obrigado.

**Comment by BenjamimCS** [comment]
Com a Issue resolvida, por favor, feche-a.
Bons estudos!
