### ISSUE TITLE
projeto login.

### ISSUE THREAD

**Issue by Angelnogueiraa** [gustavoguanabara/html-css#374]
FIz o ultimo projeto do modulo 4 que foi o projeto login mas as caixas de input e-mail e senha, estão com incopatibilidade no safari e firefox dos despositivos moveis.
Não consigo posicionar as caixas, o transform: translate não funciona. Mas no notebook está tudo funcionando em todos os navegadores.

**Comment by BenjamimCS** [comment]
Poderia mostrar um print relatando melhor o problema? Se for incompatibilidade não há o que fazer. No [MDN Web Docs](https://developer.mozilla.org/en-US/) não achei nada de incompatibilidade com o `translate`. Mesmo testando no *modo móvel* dos navegadores não achei nada de estranho. Tem certeza disso? Relate melhor, e com imagens, por favor.

Caso contrário, feche a Issue.

**Comment by Angelnogueiraa** [comment]
consegui resolver usando flex para posicionar melhor as caixas de input, agora esta compativel com todos os dispositivos, devo ter usado o translate de forma errada.
