### ISSUE TITLE
Problema no capitulo 18

### ISSUE THREAD

**Issue by kuemia** [gustavoguanabara/html-css#375]
Nao consigo publicar meu projeto usando o github!

**Comment by santosvini** [comment]
o que acontece?

**Comment by kuemia** [comment]
nao esta aparendo a opçao para poder subir o meu projeto no github pages

**Comment by santosvini** [comment]
Adiciona um print aqui na sua resposta para ver o que acontece, e como está o nome da sua pagina principal?
se n estiver index, ele n vai subir

**Comment by kuemia** [comment]
![2023-01-19](https://user-images.githubusercontent.com/92189061/213531349-31498f56-79d5-4e93-87ab-6f3388ff26c8.png)

**Comment by kuemia** [comment]
deveria aparecer a opçao de escolher o tema da pagina, porem nao aparece

**Comment by santosvini** [comment]
> ![2023-01-19](https://user-images.githubusercontent.com/92189061/213531349-31498f56-79d5-4e93-87ab-6f3388ff26c8.png)

o nome da sua pagina principal precisa ser index.html, no caso está como projetosimples.html, por padrão o pages o github usa a nomenclatura index

![image](https://user-images.githubusercontent.com/46813491/213532024-ca804148-0c98-4a8a-add9-72f61f0b9a97.png)

segue o print de um projeto que eu tenho hospedado no gh-pages, se caso vc esta configurando com Jekill, precisa ler a doc, não conheço muito sobre configurar dessa forma

![image](https://user-images.githubusercontent.com/46813491/213532432-3fcaeead-28f0-43a6-8413-f9cf752f2dbc.png)

Depois de alterar o nome da sua página, e hospedar no gh-pages, ele vai fazer o deploy e rodar um actions por default

Se ainda sim possuir duvidas, estou a disposição

**Comment by kuemia** [comment]
muito obrigado pela ajuda, deu certo
