### ISSUE TITLE
Problema com as aulas do Módulo 4

### ISSUE THREAD

**Issue by JadsonHudson** [gustavoguanabara/html-css#381]
Estava acompanhando todas as aulas, concluí os módulos 1, 2 e 3, entretanto, quando comecei o módulo 4 e, para ser mais específico, na aula 2 não consigo marcar como assistida, porque apresenta este erro da imagem a seguir.
![Erro no curso em vídeo](https://user-images.githubusercontent.com/61320947/213940229-2958bc7b-fd1d-41c0-9e78-660a651523d8.png)

**Comment by BenjamimCS** [comment]
Issue #336. Por favor, feche esta Issue.
