### ISSUE TITLE
Problema com github pages 

### ISSUE THREAD

**Issue by DouglasBorowski** [gustavoguanabara/html-css#382]
Mesmo eu comitando as alterações no vscode, minha pagina no github não abre atualizada.

**Comment by BryanDamasioBRN** [comment]
Você já esperou quanto tempo?

**Comment by devpedromelo** [comment]
Olá, poderia informar melhor quais alterações foram? se for alguma que envolve pastas, imagens, etc... verifique se as alterações estão sendo corretamente informadas no vscode, vai ver você confundiu pastas ou algo do tipo.

**Comment by BenjamimCS** [comment]
Você disse ter comitado no VSCode. Você também deu push pro GitHub?
Se sim, possa ser como você colocou seus arquivos: Issue #274 pode lhe ajudar.
Descreva melhor seu problema, por favor!

**Comment by DouglasBorowski** [comment]
foi por tempo de espera mesmo, demorou quase uma hora.
