### ISSUE TITLE
Problema com Github Pages

### ISSUE THREAD

**Issue by DarlanLima87** [gustavoguanabara/html-css#390]
Não aparece a opção do Github Pages para poder hospedar.

**Comment by andrepacifico** [comment]
Também estranhei isso, mas pelo que entendi, a configuração mudou... o que eu consegui fazer foi dentro de ''settings'' no menu da esquerda tem uma opção ''pages'' clica nela e você vai ver o ''source'' > ''deploy from a branch'' deixa a opção que aparecer e clica em ''save''. Demora um pouco pra atualizar, mas o github vai gerar o link de acesso pro teu site. Mas é um site que não tá reproduzindo tudo que EU tô codando... espero que funcione pra ti.

**Comment by DarlanLima87** [comment]
Valeu mano...tbm achei essa opção pages na lateral mas não sabia como proceder depois, vou testar isso que vc fez !!!

**Comment by kaiohcesar** [comment]
Dessa forma que o André explicou funciona sim... mas como ele falou, demora um pouco mesmo.
vai atualizando a pagina que da bom !

**Comment by Priscilaesr** [comment]
A versao esta atualizada e mudou a configuracao. Eu tambem fiz da mesma forma e funcionou :) 
Obrigada pela dica! ;)

**Comment by DarlanLima87** [comment]
Muito obrigado à todos, fiz o passo a passo que o André indicou e deu certo !
