### ISSUE TITLE
Duvida com desfio do modulo 1

### ISSUE THREAD

**Issue by Cauesoares** [gustavoguanabara/html-css#391]
o desafio do modulo 1, desafio de numero 4 fiz tudo certinho so estou uma problema que nao consigo colocar o marcador (.) grande como o gustavo fez .. 
![image](https://user-images.githubusercontent.com/124637355/217107591-410ca953-cb8a-4375-b135-4afda11d5d13.png)

**Comment by ryannardelli** [comment]
Para usar os marcadores você precisa usar a tag <ul> (para listas não ordenadas) ou <ol> (para listas ordenadas). Não se esqueça também de colocar o <li> abaixo da tag que você usou para que a lista funcione.

**Comment by ryannardelli** [comment]
Para criar marcadores você precisa utilizar a tag ul (para listas não ordenadas) ou ol (para listas ordenadas). Não se esqueça também de colocar tudo entre li, abaixo da tag que você usou, para que o código funcione.

**Comment by Cauesoares** [comment]
Vou tentar hoje a noite , se der certo retorno, se der errado tbm ksksksks . Estou começando AGR do 0 😔😔

**Comment by ryannardelli** [comment]
Ta certo. Qualquer dúvida é só falar

**Comment by Cauesoares** [comment]
Deus certo mano, brigadao sksksks

**Comment by ryannardelli** [comment]
que bom, mano. Tmj

**Comment by BenjamimCS** [comment]
Com a Issue resolvida, por favor, feche-a.
Bons estudos! 📚
