### ISSUE TITLE
Imagens - flexivel

### ISSUE THREAD

**Issue by Cauesoares** [gustavoguanabara/html-css#392]
Estou com um problema nesse desafio do modulo 1 - Desafio d007 estou completamente perdido de como fazer
o pior de tudo e que presto muito atenção nas aulas e não me lembro dele ter falado sobre isso em aulas anteriores ..

Não gostaria da respostr ou algo do tipo, gostaria de ver qual pdf ou aula ele falou sobre para que eu possa, sozinho arrumar como fazer , ficaria grato pela ajuda 

aqui estar o link do desafio - https://github.com/gustavoguanabara/html-css/blob/master/desafios/modulo-01/d007/desafio-imagem-flexivel.pdf

**Comment by BenjamimCS** [comment]
Você está anotando também? Eu sempre anoto com o vídeo linkado da aula, recomendo!
Isso é citado na [aula 3 do cap. 11 do módulo 1](https://www.youtube.com/watch?v=cAgkwPWE4hU).
