### ISSUE TITLE
Pagina do github pages

### ISSUE THREAD

**Issue by Edcleniatayna** [gustavoguanabara/html-css#394]
ja tentei de varias formas mas não consigo fazer a pagina vira o site.

**Comment by Karina-Farias** [comment]
O meu eu fiz assim : Fui em ''settings'' no menu da esquerda tem uma opção ''pages'' clica nela e você vai ver o ''source'' > ''deploy from a branch'' deixa a opção que aparecer e clica em ''save''. Demora um pouco pra atualizar, mas o github vai gerar o link de acesso pro teu site.

**Comment by Edcleniatayna** [comment]
obrigada, funcionou.

**Comment by BenjamimCS** [comment]
Com a Issue resolvida, por favor, feche-a.
