### ISSUE TITLE
ERRO 404

### ISSUE THREAD

**Issue by stefaniealexandre** [gustavoguanabara/html-css#397]
Não consigo resolver esse problema já vi o vídeo do issues #336 e não resolveu

**Comment by BenjamimCS** [comment]
No seu caso é o erro 404, que se refere a uma página não encontrada. O que foi exatamente? Terminou a aula e em seguida deu esse erro?

**Comment by stefaniealexandre** [comment]
Eu fui postar um site da aula que eu tinha feito mas no final aparece esse erro

**Comment by BenjamimCS** [comment]
Aquela Issue se refere ao curso no site, o seu caso é uma má configuração no GitHub Pages eu suponho.
Issue #274 e #204 pode ajudar. Mas já adiantando, veja se o HTML principal está na raiz do repositório nomeado de `index.html`.

**Comment by stefaniealexandre** [comment]
Obrigado, Issue #274 deu certo!
