### ISSUE TITLE
Dimensão incorreta

### ISSUE THREAD

**Issue by BrunnoDuarte07** [gustavoguanabara/html-css#398]
Boa tarde Galera!

Acabei de finalizar o projeto de redes sociais do Mód 4, ficou top, porém, no celular, não se redimensionou ao tamanho da minha tela, o que sugerem ?

**Comment by BrunnoDuarte07** [comment]
tentei por o print aqui mas não consegui ;(

**Comment by BrunnoDuarte07** [comment]
![Captura de tela 2023-02-17 160327](https://user-images.githubusercontent.com/117396899/219763344-fc8b5944-ba85-4c5a-9f10-717732b317cd.png)

**Comment by BenjamimCS** [comment]
Uma forma seria sobrepor; também você pode aplicar grid e por um tamanho menor ao dispositivo (apesar de não ser o objetivo do desafio no momento); ou somente por um tamanho menor.
Pra sobrepor é simples: dê ao container do `nav` um `position: relative` e `z-index: 1` que já resolve. Caso tenha ficado curioso sobre o `z-index`, fica essa [leitura recomendada](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index).

Caso resolva, por favor, feche a Issue.

**Comment by BrunnoDuarte07** [comment]
obrigado
