### ISSUE TITLE
Exercício 012 pode ser melhorado

### ISSUE THREAD

**Issue by gafanhotos** [gustavoguanabara/html-css#4]
### Minha humilde colaboração

O [Exercício 012 de HTML](https://github.com/gustavoguanabara/html-css/tree/master/exercicios/ex012) tem uma melhoria. Dá pra compactar o vídeo no formato **webmovie**

Gosto muito do @cursoemvideo e acompanho tudo

**Comment by gustavoguanabara** [comment]
Olá! Obrigado pela colaboração! Vou ver se faço essa alteração ainda hoje!

**Comment by gafanhotos** [comment]
> Gosto muito do @cursoemvideo e acompanho tudo

Isso é a realidade!

**Comment by gustavoguanabara** [comment]
> > Gosto muito do @cursoemvideo e acompanho tudo
> 
> Isso é a realidade!

Muito obrigado!

**Comment by gustavoguanabara** [comment]
Acabou!

**Comment by gafanhotos** [comment]
Mas mas mas...
