### ISSUE TITLE
Vai ter JavaScript?

### ISSUE THREAD

**Issue by carloskauan1597** [gustavoguanabara/html-css#40]
No curso de HTML e CSS vai ter JavaScript?

**Comment by Forcery** [comment]
> No curso de HTML e CSS vai ter JavaScript?

Eu acredito que não porque no canal já tem um curso completo de js!

**Comment by Rodrigojw2014** [comment]
@carloskauan1597 Favor fechar sua issue. Gratíssimo!

**Comment by Josepaulo3444** [comment]
> No curso de HTML e CSS vai ter JavaScript?

**Boa Tarde!!**

_Eu Acho que sim, porque html,css e sem javascript seria meio estranho_

```
Console.log("bons estudos")
```
