### ISSUE TITLE
Problemas com os Arquivos do Desafio 13 (Projeto-redes-sociais)

### ISSUE THREAD

**Issue by LincolnRP01** [gustavoguanabara/html-css#404]
Bem Galera, pra quem não está conseguindo os arquivos funcionando vou deixar aqui pra vcs baixarem, um amigo meu ja tinha feito antes deles corromperem. 

[https://cdn.discordapp.com/attachments/525128549519327232/1080874714395852820/imagens.rar](url)

**Comment by mmaltivo** [comment]
Olá, não consegui achar nesse seu link, se for possível você poderia mandar para o meu e-mail? mari73924@gmail.com
