### ISSUE TITLE
Mano, alguém sabe onde tá a parte 1 do desafio 13? 

### ISSUE THREAD

**Issue by Idinaldo** [gustavoguanabara/html-css#405]
É um desafio onde c tem q fzr duas tabelas com mesclagem de células. Na pasta de desafios tem um arquivo zip pra download q tá nomeado "pacote-d013" mas acredito que seja referente a segunda parte do desafio (ou a outro desafio) pois são apenas imagens e não tem nada a ver com a parte 1 do desafio 13

**Comment by BenjamimCS** [comment]
Como já abordado na Issue #320, estes outros exercícios estão no repositório criado no capítulo 18.

**Comment by Idinaldo** [comment]
valeu mano, n tinha visto a Issue #320 e nem tinha olhado aquele repositório.
