### ISSUE TITLE
O site tá dando erro pra vcs tb?

### ISSUE THREAD

**Issue by Idinaldo** [gustavoguanabara/html-css#406]
mano, tava lá eu de boa fznd o módulo 4 do curso de html5 e css3, terminei de assistir a primeira aula do módulo, pá, me aparece aql msg q diz q teu comportamento parece o de um bot e q vc n pode prosseguir, tentei fzr logout (na página "Minha conta" tem uma parte q diz "Olá {usuario} (não é {usuario}? sair)" tentei sair por aí ) e recebi outro erro. Tá acontecendo com vcs tb? O site tá com problema?

**Comment by Idinaldo** [comment]
![fatalerror](https://user-images.githubusercontent.com/122240078/222931134-befd4017-18c9-4bcc-bcea-7e2728469789.png)
erro quando tento sair

**Comment by Idinaldo** [comment]
![forbidden](https://user-images.githubusercontent.com/122240078/222931161-8fb85dd5-965d-4adb-96d2-19d0f3d0e76a.png)
erro ao tentar marcar a aula como concluída

**Comment by BenjamimCS** [comment]
Teve um pessoal tendo esse problema de permissão na Issue #336. O site tá realmente quebrado desde o final do ano passado :(

**Comment by Idinaldo** [comment]
mano, consegui resolver marcando a aula como concluída pelo cell, aí o site voltou ao normal no notebook tbm. vou fechar a issue
