### ISSUE TITLE
Aulas em pdf

### ISSUE THREAD

**Issue by RafaelGomesdeOliveira** [gustavoguanabara/html-css#407]
Bom dia, boa tarde ou boa noite, eu gostaria de tirar uma dúvida em relação as aulas em pdf, eu só estou tendo acesso até o capítulo 20, Mini-projeto Cordel, os demais não aparecem, 21, 22, 23...

**Comment by BenjamimCS** [comment]
Não sei se você encontrou uma forma, mas na Issue #357 tem uma solução.
