### ISSUE TITLE
Capítulo 19 Aula 07 da Plataforma Curso em Vídeo

### ISSUE THREAD

**Issue by rogertbatista** [gustavoguanabara/html-css#412]
Não estou conseguindo avançar para a primeira aula do capítulo 20. Espero a aula terminar e clico para marcar como concluído, porém me direciona para uma página com uma mão vermelha dizendo que a ação foi negada. Agradeceria se alguém pudesse me responder.

**Comment by BenjamimCS** [comment]
Houve algo similar na Issue #336.

**Comment by rogertbatista** [comment]
Já voltou à normalidade, obrigado!

**Comment by BenjamimCS** [comment]
> Já voltou à normalidade, obrigado!

O site tem tido esses problemas desde novembro do ano passado. Vasculhando por aqui nas Issues você encontra mais desses problemas bem similares ao seus.

Caso você considere como resolvido, feche esta Issue, por favor.
