### ISSUE TITLE
Problemas na parte 1 do desafio do capítulo 21

### ISSUE THREAD

**Issue by brenodevlooper** [gustavoguanabara/html-css#418]
Não há a pasta desse desafio disponível para baixar no Github, no vídeo fala que é o desafio 13, entretanto, atualmente este desafio é referente ao módulo 4 do curso.

**Comment by BenjamimCS** [comment]
Esse desafio 13 do Modulo 3 do cap. 21 tá no repositório da [conta criada em aula](https://github.com/professorguanabara/html-css).
