### ISSUE TITLE
Mini-projeto Cordel. Page not found.

### ISSUE THREAD

**Issue by Felipesouzacunha** [gustavoguanabara/html-css#425]
Não estou conseguindo baixar os arquivos para realizar o projeto. Alguém mais com esse problema?

**Comment by BenjamimCS** [comment]
Page not found? Por onde você baixou? Os materiais tão aqui no GitHub tudo certinho, mano.

**Comment by Felipesouzacunha** [comment]
Pior que não consegui baixar não. Mas entrei no github de um dos alunos e consegui pegar as imagens. to conseguindo fazer o projeto kkkk
