### ISSUE TITLE
Menu Hambúrger com problema

### ISSUE THREAD

**Issue by Luispdo** [gustavoguanabara/html-css#429]
Depois de criado o Menu Hamburger e ajustá-lo para telas maiores, o mesmo não some ao aumentar a tela, a única diferença do código do Gustavo, é o código para o icone do menu burger, o gustavo usa '<'i>/ e agora no site o código é '<'span>. Alguém sabe como resolver esse problema?

**Comment by Renato-de-Lima** [comment]
Conseguiu resolver?

**Comment by Luispdo** [comment]
Não consegui, aparentemente o problema pode estar na parte em Java e ainda estou no HTML e CSS.
Segue print. O menu hambúrger não desaparece em tela grande, como deveria fazer.
![image](https://user-images.githubusercontent.com/129074831/235315209-0b9a36e7-a83d-404b-b1e6-922ed993a2af.png)

**Comment by BenjamimCS** [comment]
Você já definiu alguma `@media`?
