### ISSUE TITLE
Problemas com o desafio 11 no Módulo 02

### ISSUE THREAD

**Issue by iamlucasmagalhaes** [gustavoguanabara/html-css#430]
Terminei o módulo 02 recentemente e comecei a fazer os desafios, porém no desafio 11 eu não consegui colocar uma imagem sobre a outra, alguém conseguiu fazer?

**Comment by michellycruz** [comment]
> Terminei o módulo 02 recentemente e comecei a fazer os desafios, porém no desafio 11 eu não consegui colocar uma imagem sobre a outra, alguém conseguiu fazer?

o 11 você vai usar o background image, vai aprender mais pra frente a fazer esse desafio, deixa ele pra depois.

**Comment by iamlucasmagalhaes** [comment]
Entendi,obrigado.
