### ISSUE TITLE
Não consigo assistir os videos do curso em video.

### ISSUE THREAD

**Issue by vitordsg** [gustavoguanabara/html-css#441]
Alguém já passou por isso? tinha voltado ao normal, consegui assistir uma aula e depois na hora de ir para a próxima, apareceu esse erro do site.

https://vitordsg.github.io/html-css-cursoemvideo/ajuda/ajuda.html

**Comment by DevKally** [comment]
@vitordsg pra mim já apareceu, lembro de ter esperado um pouco e atualizado e normalizou.
Não sei o que pode ter sido, talvez apenas o algoritmo não tenha identificado a visualização completa da aula.

**Comment by vitordsg** [comment]
Já voltou ao normal, acontece as vezes isso, muito obrigado pela ajuda.
