### ISSUE TITLE
Problema no desafio android

### ISSUE THREAD

**Issue by temirei** [gustavoguanabara/html-css#465]
Sobre as imagens do site android, na parte de responsividade: fiz tudo certinho como o professor mostrou, mas na hora de visualizar em tela menor, as imagens não trocam

**Comment by LaramosGalion** [comment]
Teria como mandar o codigo que tu escreveu? assim seria mais facil visualizar o erro

**Comment by temirei** [comment]
https://github.com/temirei/projeto-android/blob/main/index.html

https://github.com/temirei/projeto-android/blob/main/style.css

**Comment by LaramosGalion** [comment]
Já vi, pelo que deu para ver tu colocou as mesmas imagens, teria que substituir pela pequena

**Comment by LaramosGalion** [comment]
substituindo os seu sources por isso funcionou aqui:
                <source media="(max-width: 600px)" srcset="imagens/irina-blok-pq.jpg" type="image/png">
                <source media="(max-width: 600px)" srcset="imagens/dan-droids-pq.png" type="image/png">

provavelmente foi algum erro de digitação

**Comment by LaramosGalion** [comment]
provavelmente foi algum erro de digitação, dessa for aqui foi, usei o seu repositório para arrumar

`  <source media="(max-width: 700px)" srcset="imagens/dan-droids-pq.png" type="image/png">`
`                <source media="(max-width: 600px)" srcset="imagens/irina-blok-pq.jpg" type="image/png">`

**Comment by temirei** [comment]
obrigado. deu certo
