### ISSUE TITLE
Só tenho a agradecer!!!!

### ISSUE THREAD

**Issue by RickHerculano** [gustavoguanabara/html-css#48]
Olá Gustavo, sou inciante neste mundo da programação, neste momento que escrevo tenho assistido suas aulas de HTML, Javascript, CSS e agora no Git e Github e sua didática é fantástica, estou aprendendo programação com você melhor que meus professores do meu curso técnico (me desculpe se não estou sendo ético aqui!) 
Espero de coração que você sempre realize os sonhos de todos que querem entram nesse mundo do Hello World, cara seu lugar no seu está garantido! É muito difícil pessoas como você querer passar conhecimento, porque não adianta conhecimento e depois morrer e levar consigo não é mesmo! Não fazer diferença neste mundo (pra melhor claro) é burrice!

Um abraço!!!!

**Comment by Rodrigojw2014** [comment]
@RickHerculano Favor fechar sua Issue! Gratíssimo
