### ISSUE TITLE
PDFs inválidos. Não consigo baixa nenhum pdf do Módulo 1 de HTML e CSS

### ISSUE THREAD

**Issue by IlvaniSabatini** [gustavoguanabara/html-css#494]
Não consigo baixa nenhum pdf do Módulo 1 de HTML e CSS

**Comment by covolan** [comment]
Olá! 
Testei o download e parece estar funcionando corretamente.

O link para o pdf seria o seguinte:
https://github.com/gustavoguanabara/html-css/blob/master/aulas-pdf/01%20-%20Hist%C3%B3ria%20da%20Internet.pdf

E então basta clicar no ícone de download do lado direito:
![image](https://github.com/gustavoguanabara/html-css/assets/82233795/8f809ea4-3e91-41d1-9b38-6c33451e813e)

Se o botão não estiver aparecendo, clique nos 3 pontos (...) e clique em download:
![image](https://github.com/gustavoguanabara/html-css/assets/82233795/956a932c-7b2d-47bd-a4ef-bd89adc28e5e)

Se ainda sim persistir, pode tentar o atalho para download pressionando "ctrl" + "shift" +"s".

**Comment by alefyrezendesign** [comment]
![image](https://github.com/gustavoguanabara/html-css/assets/145800106/797aac7f-ee56-4831-8cf4-54c17ee3ef64)

**Comment by IlvaniSabatini** [comment]
Acho que era minha internet o problema.
