### ISSUE TITLE
problema no repositorio

### ISSUE THREAD

**Issue by eduardo-ux** [gustavoguanabara/html-css#498]
eu criei um repositorio aqui, so que ele so abre o readme, nao consigo navegar entre meus exercicios...

**Comment by Valdemirobenvindo** [comment]
No modolo 3 de HTML e CSS o professor Gustavo Guanabara ele mostra
detalhada mente como abrir os nossos exercícios no README tenta ver os
vídeos mas uma vez!😊

A quinta, 5/10/2023, 17:51, eduardo-ux ***@***.***> escreveu:

**Comment by Cosmonautta** [comment]
Tive o mesmo problema, mas o erro era nos nomes das pastas que nao estavam exatamente iguais.

**Comment by filipebatistateixera** [comment]
Bom dia, aqui pra mim só tem o PDF até o capítulo 20, é só pra mim ou está assim pra mais alguém?

**Comment by Cosmonautta** [comment]
O mesmo aqui

**Comment by eduardo-ux** [comment]
aqui tambem.
