### ISSUE TITLE
Aulas YouTube x Aulas PDF

### ISSUE THREAD

**Issue by HugoPDF5** [gustavoguanabara/html-css#5]
Olá Guanabara, percebi que a playlist do youtube possui 36 vídeos, e os PDF's aqui só tem 8. Serão adicionadas mais aulas?

**Comment by gustavoguanabara** [comment]
Fala, Hugo! Esse curso do YouTube não está seguindo exatamente esse novo material. Vou remodelar o curso de HTML5 junto com alunos apoiadores, e isso vai acontecer já na próxima semana. Serão gravados novos vídeos. O curso antigo continua valendo, mas teremos uma nova didática e abordagem. Adicionaremos novos materiais em PDF, mas teremos novas aulas em vídeo também, mas apenas liberados para apoiadores do projeto no site do [ApoieMe](apoie.me/cursoemvideo) (qualquer faixa de contribuição)

**Comment by AntonioCarlos25** [comment]
Professor, existe alguma possibilidade de criarmos um novo projeto para esse curso junto com o curso de Git e Github? Assim todos poderiam participar e contribuir no projeto.

**Comment by gustavoguanabara** [comment]
Que novo projeto? Explica direito aí.

**Comment by HugoPDF5** [comment]
> Fala, Hugo! Esse curso do YouTube não está seguindo exatamente esse novo material. Vou remodelar o curso de HTML5 junto com alunos apoiadores, e isso vai acontecer já na próxima semana. Serão gravados novos vídeos. O curso antigo continua valendo, mas teremos uma nova didática e abordagem. Adicionaremos novos materiais em PDF, mas teremos novas aulas em vídeo também, mas apenas liberados para apoiadores do projeto no site do [ApoieMe](apoie.me/cursoemvideo) (qualquer faixa de contribuição)

Obrigado pelo retorno professor, vou ficar no aguardo

**Comment by AntonioCarlos25** [comment]
> Que novo projeto? Explica direito aí.

Algum outro tipo de site, por exemplo no curso do YouTube, curso muito bom inclusive, nós criamos aquele site que apresenta o Google Glass, agora podíamos criar outro, talvez um e-commerce ou algo mais simples, tanto pra praticar com as aulas de HTML quanto pra praticar com as aulas do GitHub.
Você podia falar disso em uma das lives e ver se o pessoal topa, aí eles podem dar ideias sobre esse projeto também.

**Comment by BrenoAV** [comment]
> Fala, Hugo! Esse curso do YouTube não está seguindo exatamente esse novo material. Vou remodelar o curso de HTML5 junto com alunos apoiadores, e isso vai acontecer já na próxima semana. Serão gravados novos vídeos. O curso antigo continua valendo, mas teremos uma nova didática e abordagem. Adicionaremos novos materiais em PDF, mas teremos novas aulas em vídeo também, mas apenas liberados para apoiadores do projeto no site do [ApoieMe](apoie.me/cursoemvideo) (qualquer faixa de contribuição)

Professor @gustavoguanabara , sei que as aulas são para a galera do apoie me, mas o senhor vai continuar postando os desafios aqui nesse repositório mesmo sem sair as aulas no canal Curso em Vídeo? Fiz todo o curso antigo (2013) e estou exercitando por esses desafios (até criei um repositório público para esses desafios com as minhas respostas). Grato pela atenção!

**Comment by vitoriona** [comment]
> > Que novo projeto? Explica direito aí.
> 
> Algum outro tipo de site, por exemplo no curso do YouTube, curso muito bom inclusive, nós criamos aquele site que apresenta o Google Glass, agora podíamos criar outro, talvez um e-commerce, blog ou algo mais simples, tanto pra praticar com as aulas de HTML quanto pra praticar com as aulas do GitHub.
> Você podia falar disso em uma das lives e ver se o pessoal topa, aí eles podem dar ideias sobre esse projeto também.

A iniciativa agora pode vir dos inscritos. Da para criar uma iniciativa assim e já utilizarmos os conhecimentos adquiridos com o novo curso de GIT e GitHub. Realizando Fork e Pull Request 😀

**Comment by christyanbrayan** [comment]
@BrenoAV as aulas vão ser disponibilizadas primeiramente no apoie me, mas quando o curso for finalizado, talvez no ano que vem, o curso todo será disponibilizado no canal para todos os inscritos. O prof disse isso em uma das lives do curso de Git e GitHub.

Quanto a esse repositório, não sei se sairão mais desafios, como é focado aos alunos presenciais dele, talvez continue por algum tempo. Quem deu star nesse repositório desde o seu início viu que a cada semana ele ia "commitando" mais coisa. Uma hora talvez ele conclua, mas por enquanto ele vem atualizando de tempos em tempos.

@vitoriona a ideia é boa, poderíamos até compartilhar com o Guanabara em alguma das lives ou de outra forma, com certeza ele iria gostar e apoiar.

**Comment by AntonioCarlos25** [comment]
> > > Que novo projeto? Explica direito aí.
> > 
> > 
> > Algum outro tipo de site, por exemplo no curso do YouTube, curso muito bom inclusive, nós criamos aquele site que apresenta o Google Glass, agora podíamos criar outro, talvez um e-commerce, blog ou algo mais simples, tanto pra praticar com as aulas de HTML quanto pra praticar com as aulas do GitHub.
> > Você podia falar disso em uma das lives e ver se o pessoal topa, aí eles podem dar ideias sobre esse projeto também.
> 
> A iniciativa agora pode vir dos inscritos. Da para criar uma iniciativa assim e já utilizarmos os conhecimentos adquiridos com o novo curso de GIT e GitHub. Realizando Fork e Pull Request 😀
> 
> A iniciativa pode começar aqui: https://bit.ly/2Vlai1x
> E não só para essa iniciativa, mas podemos usar o grupo para compartilharmos conhecimentos :)

Sim é uma ótima ideia, espero que mais pessoas participem

**Comment by christyanbrayan** [comment]
@HugoPDF5 fecha a issue
