### ISSUE TITLE
Por que os PDFs de todas as aulas de HTML5 não estão mais disponíveis?

### ISSUE THREAD

**Issue by Gabriel-ds** [gustavoguanabara/html-css#51]
Antes no repositório html-css tinha todas as aulas em PDF do curso, inclusive aulas mais avançadas. Hoje só está disponível 5 aulas.

**Comment by romulocpaiva** [comment]
Creio que ele esteja atualizando o conteúdo do material.

**Comment by irvinglucas** [comment]
Ele está atualizando os PDFs e liberando à medida que vai passando as aulas, pelo que pude observar.

**Comment by kaizematicabr** [comment]
Por que não consigo encontrar os PDFs de aulas mais recentes do que a aula 4 do HTML e CSS?
O que estou fazendo de errado?

Grato por uma orientação
William

**Comment by Sidney-Scholze** [comment]
Lá no meu GitHub tem os PDFs [Aqui](https://github.com/Sidney-Scholze/html-css/tree/main/PDFs)

**Comment by irvinglucas** [comment]
> Por que não consigo encontrar os PDFs de aulas mais recentes do que a aula 4 do HTML e CSS?
> O que estou fazendo de errado?
> 
> Grato por uma orientação
> William

### **Você não fez nada de errado.**

Quando você clona o repositório na sua máquina ou abre ele aqui no site, você está visualizando o estado **atual** do repositório, ou seja, o repositório foi manipulado para ficar como está atualmente. Houve um momento onde tinham vários PDFs disponíveis, porém quando o curso começou, ele "removeu" da pasta vários PDFs de aulas mais avançadas e realizou um commit com a mudança. Dessa forma, os PDFs "sumiram" e só é possível visualizar os que foram mantidos. 

Recomendo fortemente o [Curso de Git e GitHub](https://www.cursoemvideo.com/course/curso-de-git-e-github/) do @gustavoguanabara também. Vai ajudar bastante a entender esses conceitos, bem como agregar uma ferramenta importantíssima para a sua vida de programador ;)

**Comment by kaizematicabr** [comment]
Muito obrigado,Irving
Valeu, mesmo.
Já estou na primeira aula do curso sugerido.
Grato
William

    On Saturday, October 24, 2020, 4:59:51 PM GMT-3, Irving Lucas da Silva Melo <notifications@github.com> wrote:  
 
 



Por que não consigo encontrar os PDFs de aulas mais recentes do que a aula 4 do HTML e CSS?
O que estou fazendo de errado?

Grato por uma orientação
William


Você não fez nada de errado.

Quando você clona o repositório na sua máquina ou abre ele aqui no site, você está visualizando o estado atual do repositório, ou seja, o repositório foi manipulado para ficar como está atualmente. Houve um momento onde tinham vários PDFs disponíveis, porém quando o curso começou, ele "removeu" da pasta vários PDFs de aulas mais avançadas e realizou um commit com a mudança. Dessa forma, os PDFs "sumiram" e só é possível visualizar os que foram mantidos.

Recomendo fortemente o Curso de Git e GitHub do @gustavoguanabara também. Vai ajudar bastante a entender esses conceitos, bem como agregar uma ferramenta importantíssima para a sua vida de programador ;)

**Comment by Rodrigojw2014** [comment]
Favor @Gabriel-ds  fechar sua Issue. Gratíssimo.
