### ISSUE TITLE
Problema no capítulo 18 hospedando o projeto Android 

### ISSUE THREAD

**Issue by EliaFraga** [gustavoguanabara/html-css#510]
Quando eu abro o projeto no vs Code ele carrega a fonte Android porém quando eu hospedo ele no Github a fonte não carrega, o que pode ser?

**Comment by BenjamimCS** [comment]
Olá amigo. Não sei se já resolveu, mas suponho que esteja indicando o caminho dos diretórios relativas ao seu próprio ambiente. Na Issue #197 tem um problema parecido.

**Comment by EliaFraga** [comment]
Resolvido Obrigado em!!

**Comment by BenjamimCS** [comment]
Com a Issue resolvida feche-a por favor.
