### ISSUE TITLE
Modulo4 Duvida Sobre os PDF

### ISSUE THREAD

**Issue by shydersonalves** [gustavoguanabara/html-css#515]
Queria saber se tem disponível o pdf do modulo 4 em alguma outra plataforma, ou somente ainda não tem?

**Comment by thiagowanderley** [comment]
Segue Link com todos os materiais https://github.com/gustavoguanabara/html-css/tree/fe6653ecdafa5b7275a5ecb4c36a8ca14f5043e7/aulas-pdf : )

**Comment by shydersonalves** [comment]
Obrigado, cap 22 não estava aparecendo! : )
