### ISSUE TITLE
Curso JavaScript/Modulo D/Aula 11

### ISSUE THREAD

**Issue by gabrieldreher** [gustavoguanabara/html-css#525]
Acho que o prof. esqueceu de resolver o exercício que ele pediu para a gente fazer no final da aula 11 do módulo D.

Eu fiz mas não está funcionando de jeito nenhum, se alguém puder me dar uma luz!
Segue:
````
<body>
    <h1>Sua Nacionalidade</h1>
    <label for="txtnac">Onde você vive?</label>
     <input type="text" name="txtnac" id="txtnac">
    <input type="button" value="Verificar" onclick="verif()">
    <div id="res">

    </div>

    <script>
        function verif() {
            var nac = window.document.querySelector('input#txtnac')
            var res = window.document.querySelector('div#res')

                res.innerHTML = `Vivendo em ${nac},`
                if (nac == `Brasil`) {
                    res.innerHTML += `<p>Você é Brasileiro(a)!</p>`
                }else {
                    res.innerHTML += `<p>Você é estrangeiro(a)!</p>`
                }
        }
    </script>
</body>
````
Valeu!

**Comment by jefersonssant** [comment]
Oi meu amigo, tudo bem? Vou tentar ajudar. Na sua primeira variável acrescente ao final _**.value**_ exemplo abaixo:

`var nac = window.document.querySelector('input#txtnac').value`

Execute novamente e depois me retorne se conseguiu.

**Comment by jefersonssant** [comment]
Por nada, tmj! No input text temos de capturar o que a pessoa digita, o seu valor, por isso o _.value_.

**Comment by gabrieldreher** [comment]
Pode crer!
Acho que agora eu aprendi direitinho
Valeu novamente!
