### ISSUE TITLE
problemas no capitulo 18

### ISSUE THREAD

**Issue by DavidLucas97** [gustavoguanabara/html-css#570]
estou com problema para colocar o site no ar, faço todo procedimento na github pages, mais quando abro pelo link só abre uma tela branca, falaram que demora um pouquinho pra carrega, mais deixei horas e não foi, e sempre depois de realizar o procedimento eu recebo a seguinte msg no e-mail ( pages build and deployment cancelado)

**Comment by BenjamimCS** [comment]
Provável do seu `index.html` ou `readme.md` estarem vazios pois o seu navegador não reportou nenhum erro de página não encontrada (404) mas apenas uma página em branco.

**Comment by DavidLucas97** [comment]
BenjamimCS
Mais qual será a razão, porque fiz passo a passo da aula várias vezes e mesmo assim não consigo, e não é só o do HTML 
Todos que tento o link que o Pages gera não abre nenhum, ele basicamente abre a tela branca só com o título do site, mais o conteúdo em si não abre

**Comment by hugobrambati** [comment]
O meu demorou bastante ate subir, e o github pages está diferente de quando a aula foi feita.

**Comment by BenjamimCS** [comment]
> BenjamimCS Mais qual será a razão, porque fiz passo a passo da aula várias vezes e mesmo assim não consigo, e não é só o do HTML Todos que tento o link que o Pages gera não abre nenhum, ele basicamente abre a tela branca só com o título do site, mais o conteúdo em si não abre

O que você colocou nesee arquivo? O GitHub Pages abre na raiz do repositório esses arquivos que já citei. Se você não popular é esse resultado mesmo que você vai ter.

**Comment by Shima20Hamada** [comment]
Tive um problema parecido, quando eu tentava hospedar aparecia tela branca, para resolver eu criei um repositório em uma pasta vazia, depois eu passei os arquivos que fazem o site funcionar nessa pasta e enviei para o repositório, após isso o link já abria direto no site criado.

**Comment by DavidLucas97** [comment]
Brigado pessoal
Agora foi
Fui tentando um pouco de cada kkk
Deu certo agora
Brigado
