### ISSUE TITLE
Problema no github

### ISSUE THREAD

**Issue by murilosheesh** [gustavoguanabara/html-css#572]
Eu ja consegui publicar meu repositório de HTML e CSS, porém, sempre qnd crio uma pasta nova ou faço uma alteração em uma pasta ja existente no meu repositório, mesmo dando commit e origin, ele nao vai para meu repositório, so consegui fazer ate o exercicio 21, o resto nao vem pro GitHub.

**Comment by BenjamimCS** [comment]
> Eu ja consegui publicar meu repositório de HTML e CSS, porém, sempre qnd crio uma pasta nova ou faço uma alteração em uma pasta ja existente no meu repositório, mesmo dando commit e origin, ele nao vai para meu repositório, so consegui fazer ate o exercicio 21, o resto nao vem pro GitHub.

Poderia mostrar com imagens? Você deu commit e `origin`... `origin` você se refere ter feito um `push` ao repositório? Muito estranho, até porque devia ter acontecido algum erro.

**Comment by thayspradoo** [comment]
> Eu ja consegui publicar meu repositório de HTML e CSS, porém, sempre qnd crio uma pasta nova ou faço uma alteração em uma pasta ja existente no meu repositório, mesmo dando commit e origin, ele nao vai para meu repositório, so consegui fazer ate o exercicio 21, o resto nao vem pro GitHub.

Assim o vídeo do Capítulo 19 Aula 02, e você vai conseguir criar e alterar as pastas!

**Comment by murilosheesh** [comment]
> Amigo, você inicia abrindo sempre o GitHub Desktop antes mesmo do Visual Code? Eu tava errando nessa parte, eu abria o Visual ou criava uma pasta antes de abrir o Git no Desktop 😅

nao, eu primeiro abro o git desktop e dps aperto em abrir com o vs code.

**Comment by murilosheesh** [comment]
> > Eu ja consegui publicar meu repositório de HTML e CSS, porém, sempre qnd crio uma pasta nova ou faço uma alteração em uma pasta ja existente no meu repositório, mesmo dando commit e origin, ele nao vai para meu repositório, so consegui fazer ate o exercicio 21, o resto nao vem pro GitHub.
> 
> Poderia mostrar com imagens? Você deu commit e `origin`... `origin` você se refere ter feito um `push` ao repositório? Muito estranho, até porque devia ter acontecido algum erro.

sim, eu faço qualquer alteraçao e dps  dou commit e origin e nao muda nada no repositório, supondo, se eu for tentar escrever algo no READ ME e dps dar commit e push nao muda nada no repositório.

**Comment by murilosheesh** [comment]
> > Eu ja consegui publicar meu repositório de HTML e CSS, porém, sempre qnd crio uma pasta nova ou faço uma alteração em uma pasta ja existente no meu repositório, mesmo dando commit e origin, ele nao vai para meu repositório, so consegui fazer ate o exercicio 21, o resto nao vem pro GitHub.
> 
> Assiste o vídeo do Capítulo 19 Aula 02, e você vai conseguir criar e alterar as pastas!

ja vi

**Comment by murilosheesh** [comment]
resolvi o problema
