### ISSUE TITLE
Não consigo acessar o github pelo computador 

### ISSUE THREAD

**Issue by Solislo** [gustavoguanabara/html-css#576]
Estudo pelo computador, mas toda vez que tento abrir o github para vê os desafios eu não consigo abrir, diz que o site tá em outro local.

**Comment by BenjamimCS** [comment]
Aqui não é um bom lugar para essa pergunta, recomendo que faça no StackOverlfow, mas já adianto que veja se  não há nenhum bloqueio no firewall.
