### ISSUE TITLE
Duvida sobre as media queries

### ISSUE THREAD

**Issue by DanielRibeiro2557** [gustavoguanabara/html-css#577]
No arquivo style.css ou invés de usar:
```
@media screen and (min-width: 768px) and (max-width: 992px){

}
```
Eu não posso usar:
```
@media screen and (768px <= width <= 992px) {
    
}
```

**Comment by BenjamimCS** [comment]
Dá sim, [veja o que diz no MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries#targeting_media_features "Using media queries - CSS: Cascadian Style Sheets | MDN"):
> With media query range features, you can either use the inclusive min- and max- prefixes or the more concise range syntax operators <= and =>.
>  The following media queries are equivalent:
> ```CSS
>  
>  @media (min-width: 30em) and (max-width: 50em) {
>    /* … */
>  }
>  
>  @media (30em <= width <= 50em) {
>    /* … */
>  }
> ```

`<=` e `=>` são os mesmos que min- e max- respectivamente. E essa sintaxe com intervalos também é válida.

Muito boa sua pergunta. Dá uma lida nesse artigo do MDN, especificamente em *Targeting media features*.

Acho ser algum novo recurso pois nunca vi alguém usando um recurso tão elegante nas CSSs ou apenas desconhecido.

**Comment by DanielRibeiro2557** [comment]
OK obrigado
