### ISSUE TITLE
Onde está o gabarito dos PDF´s?

### ISSUE THREAD

**Issue by juliogabrielxp** [gustavoguanabara/html-css#580]
Galera posso tá fazendo uma pergunta burra, nunca usei o Git, e sei que não é tão difícil as perguntas no final, mas só queria ter certeza se tem algum gabarito?

**Comment by BenjamimCS** [comment]
Fique à vontade para perguntar.
Se não me engano não tem gabarito. De dica sempre pesquise sobre até você se assegurar do que está lidando.

**Comment by juliogabrielxp** [comment]
Ta ok, muito obrigado
