### ISSUE TITLE
Teste os seus conhecimentos - Sugestão

### ISSUE THREAD

**Issue by riagva** [gustavoguanabara/html-css#6]
Prof. @gustavoguanabara, nas fichas PDF "Teste os seus conhecimentos", as perguntas poderiam estar numeradas? Penso que seja mais fácil, em caso de dúvidas dizermos que é a pergunta "_x_" do tema "_y_" do que estar a transcrever toda a pergunta para se tirar as dúvidas, caso existam.

**Comment by gustavoguanabara** [comment]
BOOOOA! Vou numerar sim! Você tem toda razão! Eu também estava pensando em abrir umas issues pra galera que está fazendo o curso de HTML sugerir questões de múltipla escolha para facilitar minha vida. O que acha?

**Comment by riagva** [comment]
> BOOOOA! Vou numerar sim! Você tem toda razão! Eu também estava pensando em abrir umas issues pra galera que está fazendo o curso de HTML sugerir questões de múltipla escolha para facilitar minha vida. O que acha?

Também é uma boa ideia, tipo um quiz ;)

Grande abraço.

**Comment by christyanbrayan** [comment]
@riagva fecha a issue

**Comment by riagva** [comment]
Assunto resolvido, issue fechada ;)
