### ISSUE TITLE
Problemas com a fonte Android do capitulo 18!!!!

### ISSUE THREAD

**Issue by DaniMorimoto** [gustavoguanabara/html-css#616]
Preciso de ajuda!! A font android funciona apenas no notebook, quando leio o QRcode do meu site com o celular, a font Android não funciona, já tentei tanto em IOS quanto em Android. O caminho esta correto! , já tentei de tudo! agr quando abro o site do guanabara a font aparece no celular certinho, mais o codigo está igual, alguém me ajuda por favorrr!!!!!!

**Comment by Jhown-glitch** [comment]
Você tentou declarar a fonte no html? comigo algumas fontes só funcionaram quando declarei no html, não sei se errei ao declarar no css.

**Comment by BenjamimCS** [comment]
_De novo essa de código igual porém não funciona, haha!_ Já diz o mestre: se tivesse igual funcionaria.

Vamos por partes:
* A fonte android é definida usando a regra `@font-face`
  * provável do caminho da fonte está  errado ou a sintaxe está errada em alguma parte da regra.
* O deploy (ato de atualizar a página de acordo com o seu último commit) toma tempo. Talvez possa ser cache, então limpe o cache.
* Funcionar no seu notebook você diz quando abre o arquivo pelo VSCode com alguma extensão como o Live Server ou direto do site gerado pelo GitHub Pages?

Tem uma ferramenta para debugar seu código chamada DevTools, está presente em todos os navegadores. Já falei sobre na Issue #332. Recomendo aprender a usá-la.

Se puder trazer um pouco do código, das partes que você considera haver erro seria de grande ajuda.

**Comment by DaniMorimoto** [comment]
> Você tentou declarar a fonte no html? comigo algumas fontes só funcionaram quando declarei no html, não sei se errei ao declarar no css.

Obrigada, funcionou ❤️

**Comment by DaniMorimoto** [comment]
@Jhown-glitch Me salvou ❤️!!!
