### ISSUE TITLE
Não aparece a opção Envelope com Abreviatura 

### ISSUE THREAD

**Issue by Gabriel12211** [gustavoguanabara/html-css#62]
Na aula de Negrito e Itálico, a opção Envelope com abreviatura não apareceu. Alguém pode me ajudar ? Estou travado na aula pq não consegui achar a opção
![image](https://user-images.githubusercontent.com/73496034/100638192-7d53bd80-3312-11eb-8400-8a2b6cbe4a59.png)

**Comment by WSantos79** [comment]
Apareceu sim, note que na sua print tem a opção "Emmet: Wrap with Abbreviation"... Conforme marquei para  você em sua print: 
![image](https://user-images.githubusercontent.com/58752564/100668851-682a5f00-3311-11eb-91ab-3be575dfda62.png)

**Comment by Gabriel12211** [comment]
Poooo manin, vlw. É que a tradução br ficou diferente da do vídeo, ai buguei todo. Obrigado mesmo!!
