### ISSUE TITLE
Cadê o PDF da aula de links?

### ISSUE THREAD

**Issue by Gustavonobreza** [gustavoguanabara/html-css#63]
## A [aula](https://www.youtube.com/watch?v=LeOVXQDsAIY) foi lançada no YouTube, ele (o mestre Splinter) cita o material em PDF mas aqui no repositório eu não encontro.

# &#x2639;

**Comment by lucianogardim** [comment]
Também gostaria.

**Comment by loaalobo** [comment]
também estou esperando

**Comment by willy-r** [comment]
Olá @Gustavonobreza, você pode encontrar o PDF do capítulo 10 [aqui](https://github.com/gustavoguanabara/html-css/blob/master/aulas-pdf/10%20-%20Liga%C3%A7%C3%B5es%20em%20toda%20parte.pdf). 😃

**Comment by Gustavonobreza** [comment]
## Boa noite @willy-r,  **Muito Obrigado !!!**
### Você ajudou muito!

**Comment by Gustavonobreza** [comment]
# Aprendi a feichar a issue :laughing:
