### ISSUE TITLE
Listas

### ISSUE THREAD

**Issue by hugoleoc** [gustavoguanabara/html-css#64]
Tentei montar uma lista ordenada com alguns subitens e pulando alguns itens, porém não consegui, alguém tem alguma ideia de como poderia fazer?
obs.: a utilização da lista é para capítulos e subcapítulos de um livro que estou estudando.
Exemplo:
1. item
1.1. subitem
1.2. subitem
2. item
2.3. subitem
2.5. subitem
Gostaria de ao menos conseguir criar os subitens contínuos.

**Comment by WSantos79** [comment]
Opa, eu fiz utilizando o CSS:

 no HTML :

    <ol>
        <li>item X</li>

        <ol>
            <li>subitem Y</li>
            <li>subitem Y</li>
            <li>subitem Y</li>
        </ol>
        
        <li>item Y</li>

        <ol>
            <li>subitem X</li>
            <li>subitem X</li>
            <li>subitem X</li>
        </ol>
    </ol>

E no CSS : 

ol { counter-reset: item } 
li { display: block }        
li:before { content: counters(item, ".") " "; counter-increment: item }

Resultado : 
![image](https://user-images.githubusercontent.com/58752564/101294788-a1117a80-37ce-11eb-94bf-3cfba310bda1.png)

**Comment by hugoleoc** [comment]
Valeu pela ajuda WSantos!
