### ISSUE TITLE
Desafios e PDF das aulas apresentam errro de que o arquivo esta invalido

### ISSUE THREAD

**Issue by Syncler** [gustavoguanabara/html-css#65]
Boa tarde, os desfios 6, 7, 8 e 9 estão apresentando erro de arquivo invalido/inexistente
![image](https://user-images.githubusercontent.com/15165529/101533351-7b25da80-3974-11eb-946b-5bbc7e212704.png)

**Comment by matheusfelipeog** [comment]
Provavelmente é algum problema em seu ambiente ou um problema temporário na cloud de armazenamento de arquivos que o github usa.
 
Aqui todos os arquivos mencionados estão abrindo corretamente:

![image](https://user-images.githubusercontent.com/50463866/101710672-bdccdd00-3a70-11eb-87b0-82f67beffbda.png)

Possíveis soluções para seu problema:

- Limpar o cache do seu browser e atualizar a página. (Atalho: <kbd>CRTL</kbd> + <kbd>F5</kbd>);
- Baixar o arquivo em questão no botão `Download` no canto direito superior da área onde se localiza o arquivo;
- Ou baixar todo o repositório para seu ambiente, assim terá todos os arquivos em sua maquina.
