### ISSUE TITLE
Problema no site quando abro o site no celular 

### ISSUE THREAD

**Issue by SamuelFilipe04** [gustavoguanabara/html-css#656]
tanto meu header, quanto nav, no css ou no html, está exatamente igual do professor guanabara, mas quando eu abro o site no celular no celular, a nav onde fica os menu(home, noticias, contatos), está visualmente por cima, do meu paragrafo "Tudo aquilo que você sempre quis saber sobre o mundo Tech, em um único lugar", ja tirei a margin e coloquei o padding de 50px e mesmo assim n deu.. oq sera q pode ser?

**Comment by BenjamimCS** [comment]
Veja se não há outra regra interferindo. Use o DevTools e veja você mesmo como o seu site tá se comportando.

**Comment by Warley-sc** [comment]
coloque uma foto para saber o que está está acontecendo, mas muito provavelmente é por conta da responsividade, se o site foi feita apenas para um tipo de tela ele só vai funcionar naquela tela, tente um "@media screen" para definir os padrões de comportamento para determinadas telas definindo as larguras 

> tanto meu header, quanto nav, no css ou no html, está exatamente igual do professor guanabara, mas quando eu abro o site no celular no celular, a nav onde fica os menu(home, noticias, contatos), está visualmente por cima, do meu paragrafo "Tudo aquilo que você sempre quis saber sobre o mundo Tech, em um único lugar", ja tirei a margin e coloquei o padding de 50px e mesmo assim n deu.. oq sera q pode ser?

**Comment by SamuelFilipe04** [comment]
![image](https://github.com/user-attachments/assets/ae45d9da-e4c5-45db-a166-8be1e7a64ade)

Meu nav está "embolado" no celular..

**Comment by Warley-sc** [comment]
É por causa do responsivo, o seu site não está adaptado para telas menores e por isso dá esse conflito, vc terá que usar um "@media screen " para definir a partir de que momento o site terá que se comportar de outra forma entra no site da w3scool, lá eles falam sobre como funciona a questão da responsividade

**Comment by BenjamimCS** [comment]
Pelo print só vendo o código mesmo. Você tá usando `height` no seu `header`, o prof. usou `min-height`. O problema surge quando se diminui a largura do viewport, a página.

Dica: aprenda a usar o devtools do seu navegador, é muito útil para debugar o seu código.

> Já dizia o mestre Guanabara: se tivesse igual era pra tá funcionando.

**Comment by SamuelFilipe04** [comment]
> Pelo print só vendo o código mesmo. Você tá usando `height` no seu `header`, o prof. usou `min-height`. O problema surge quando se diminui a largura do viewport, a página.
> 
> 
> 
> Dica: aprenda a usar o devtools do seu navegador, é muito útil para debugar o seu código.
> 
> 
> 
> > Já dizia o mestre Guanabara: se tivesse igual era pra tá funcionando.

Cara, pior q eu lembrei dessa frase dele e por isso conferi 50x antes de vim aqui comentar e mesmo assim deixei passar esse detalhe.. consegui aqui, mt obrigado!

**Comment by SamuelFilipe04** [comment]
> É por causa do responsivo, o seu site não está adaptado para telas menores e por isso dá esse conflito, vc terá que usar um "@media screen " para definir a partir de que momento o site terá que se comportar de outra forma entra no site da  w3schools, lá eles falam sobre como funciona a questão da responsividade 

Estava mais fácil concertar do que eu imaginei kkkk nessa época eu ainda n tinha aprendido media query e nem saberia usar o @media screen, mas mt obrigado amigo!

**Comment by BenjamimCS** [comment]
É isso mano.

Com a Issue resolvida, por favor, feche a Issue. Bons estudos!
