### ISSUE TITLE
O que tem de errado no d007?

### ISSUE THREAD

**Issue by maressasamay** [gustavoguanabara/html-css#658]
A imagem G está aparecendo, porém a M e a P não aparece, aparecendo somente os alt da G (?????) no tamanho mediano e pequeno. O que tem de errado no meu código?

`<picture>`
      `<source media="(max-width: 750px)" srcset="d007/paisagem-p.png" type="image/png">`
      
  `    <source media="(max-width: 1050px)" srcset="d007/paisagem-m.png" type="image/png">`

     <img src="paisagem-g.png" alt="paisagem g">
 `   </picture>`

**Comment by BenjamimCS** [comment]
Veja se não seja o caminho dos arquivos. A tag `img` tá com o caminho diferente das demais.

**Comment by BenjamimCS** [comment]
Caso tenha resolvido, por favor, feche a Issue.
