### ISSUE TITLE
Problema no desafio 12

### ISSUE THREAD

**Issue by raianecorrea** [gustavoguanabara/html-css#660]
Olá, fiz o projeto cordel junto com o professor e na hora de abrir no celular o efeito parallax não funcionava mais.

**Comment by mateusgdmelo** [comment]
Consegue descrever melhor o que está acontecendo? Vi o seu código no repositório e não parece ter nenhum erro. Só senti falta de um "background-repeat: no-repeat". Tenta configurar pra ver o que acontece.

**Comment by BenjamimCS** [comment]
> Olá, fiz o projeto cordel junto com o professor e na hora de abrir no celular o efeito parallax não funcionava mais.

Por acaso é um Iphone? O Safari e navegadores Safari não suportam o valor `fixed`, apesar de atualmente, a partir da versão 15.4, já oferecer suporte segundo [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment#browser_compatibility "mdn"). Mais informações na Issue #193.

**Comment by raianecorrea** [comment]
> > Olá, fiz o projeto cordel junto com o professor e na hora de abrir no celular o efeito parallax não funcionava mais.
> 
> Por acaso é um Iphone? O Safari e navegadores Safari não suportam o valor `fixed`, apesar de atualmente, a partir da versão 15.4, já oferecer suporte segundo [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment#browser_compatibility). Mais informações na Issue #193.

Sim, meu aparelho é Iphone porém eu abro os sites no Google Chrome.

Acabei de abrir o do professor no meu celular e parece estar com o mesmo 'defeito'.

**Comment by BenjamimCS** [comment]
@raianecorrea. Veja a Issue que indiquei pra entender.

**Comment by mateusgdmelo** [comment]
> > Consegue descrever melhor o que está acontecendo? Vi o seu código no repositório e parece que não tem erro. Só senti falta de um "background-repeat: no-repeat". Tenta configurar pra ver o que acontece.
> 
> ![Imagem do WhatsApp de 2024-09-10 à(s) 09 26 04_a0055d2b](https://private-user-images.githubusercontent.com/177161240/366061067-6eed7192-7750-4e88-b694-cf28425aed0c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMTE1MTUsIm5iZiI6MTcyNjAxMTIxNSwicGF0aCI6Ii8xNzcxNjEyNDAvMzY2MDYxMDY3LTZlZWQ3MTkyLTc3NTAtNGU4OC1iNjk0LWNmMjg0MjVhZWQwYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQyMzMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGZhY2E3ZGEzMzVmNWM1ZjMzYzAwOTdmMjYyNDIwZGM4M2JhM2U3YThiNDExNTQ3MDRmYmMwNmMwYTYzNzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6iX20sFx94kkq6mfEeDXg5vxq1v0f504GQhx0qZk57A) Abrindo o site no celular o efeito parallax ou seja, o background-attachamed não funciona. Acabei de adicionar a configuração que você orientou do background-repeat e segue do mesmo jeito.

Estranho mesmo. Aqui no meu celular (um motorola) abre normal:

![Imagem do WhatsApp de 2024-09-10 à(s) 20 38 18_66064edc](https://github.com/user-attachments/assets/846277a8-a368-4374-8498-023833209fef)

Deve ser o problema que o amigo citou aí mesmo.

**Comment by raianecorrea** [comment]
> @raianecorrea. Veja a Issue que indiquei pra entender melhor.

entendi, são erros de incompatibilidade... conforme avançam os estudos testarei métodos para sanar esse problema. Mesmo assim muito obrigada!

**Comment by raianecorrea** [comment]
> > > Consegue descrever melhor o que está acontecendo? Vi o seu código no repositório e parece que não tem erro. Só senti falta de um "background-repeat: no-repeat". Tenta configurar pra ver o que acontece.
> > 
> > 
> > ![Imagem do WhatsApp de 2024-09-10 à(s) 09 26 04_a0055d2b](https://private-user-images.githubusercontent.com/177161240/366061067-6eed7192-7750-4e88-b694-cf28425aed0c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMTE1MTUsIm5iZiI6MTcyNjAxMTIxNSwicGF0aCI6Ii8xNzcxNjEyNDAvMzY2MDYxMDY3LTZlZWQ3MTkyLTc3NTAtNGU4OC1iNjk0LWNmMjg0MjVhZWQwYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQyMzMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGZhY2E3ZGEzMzVmNWM1ZjMzYzAwOTdmMjYyNDIwZGM4M2JhM2U3YThiNDExNTQ3MDRmYmMwNmMwYTYzNzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6iX20sFx94kkq6mfEeDXg5vxq1v0f504GQhx0qZk57A) Abrindo o site no celular o efeito parallax ou seja, o background-attachamed não funciona. Acabei de adicionar a configuração que você orientou do background-repeat e segue do mesmo jeito.
> 
> @raianecorrea Estranho mesmo. Aqui no meu celular (um motorola) abre normal:
> 
> ![Imagem do WhatsApp de 2024-09-10 à(s) 20 38 18_66064edc](https://private-user-images.githubusercontent.com/179981872/366248668-846277a8-a368-4374-8498-023833209fef.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMTUwMzMsIm5iZiI6MTcyNjAxNDczMywicGF0aCI6Ii8xNzk5ODE4NzIvMzY2MjQ4NjY4LTg0NjI3N2E4LWEzNjgtNDM3NC04NDk4LTAyMzgzMzIwOWZlZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwMDMyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjI5NjYyY2UyODQ0YWQ4M2ZlMmE0MWRmMThiMWJjYWJkZTliYzA3ZjFlYWU0MGI4NGEwMWEyNjcyMzM3NGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZGk9MS597gZwaj3T4PeOVQBusj6Wscz11VdNA3Ov-mg)
> 
> Deve ser o problema que o amigo citou aí mesmo.

Sim, acabei de ver...uma pena, pois queria mostrar os sites para os colegas e quem é usuário Apple não vai conseguir ver mas é assim mesmo. De qualquer forma, muito obrigada!
