### ISSUE TITLE
Error no Git 

### ISSUE THREAD

**Issue by lparanhoskoda** [gustavoguanabara/html-css#663]
Boa tarde, estou com esse erro no Git desktop, o repositorio no site da github ate atualiza certinho, mas essa mensagem não some do  git. Alguem ja passou por isso?

![Captura de tela 2024-09-13 172052](https://github.com/user-attachments/assets/e1f3a8ec-c9e0-4d21-bc21-74f8aac694c8)

**Comment by BenjamimCS** [comment]
Isso acontece quando? Poderia fornecer mais detalhes?

**Comment by lparanhoskoda** [comment]
Começou no ex0025 a partir de form003.html.

**Comment by BenjamimCS** [comment]
Me refiro aos commits e branchs pois pela mensagem de erro parece ter acontecido alguma coisa no seu repositório remoto que o seu local não está de acordo.

> Aqui não é o melhor lugar para se falar de Git, sugiro que faça o curso do prof. e faça a pergunta no StackOverflow. Por enquanto vamos seguir por aqui.

**Comment by lparanhoskoda** [comment]
Problema resolvido, era um arquivo chamado "HEAD" dentro da pasta origin do git, obrigado por ter tentado ajudar !
