### ISSUE TITLE
Problema no repositorio do projeto-andorid

### ISSUE THREAD

**Issue by hideyoshijoko** [gustavoguanabara/html-css#667]
Fiz o repositorio do projeto-android, mas quando clico na url não está abrindo.

https://hideyoshijoko.github.io/projeto-android/

**Comment by BenjamimCS** [comment]
Issue #204

**Comment by BenjamimCS** [comment]
Caso tenha resolvido, por favor, encerre a issue. Senão pode perguntar, tamo aqui pra se ajudar.

**Comment by hideyoshijoko** [comment]
Acho que consegui resover. O nome do arquivo estava como "index.html.html". 
Nao sei se era isso, mas depis que concertei o link rodou de boa.
