### ISSUE TITLE
Problema no cap 18

### ISSUE THREAD

**Issue by PedroHenriquePimentel** [gustavoguanabara/html-css#676]
Estou tentando criar as paginas no github pages e da "Erro 404" o que  faço??

**Comment by BenjamimCS** [comment]
Issue #204

**Comment by PedroHenriquePimentel** [comment]
Opa, muito obrigado pela resposta! Mas ainda não consegui corrigir o erro, agr não consigo nem gerar páginas :(

**Comment by BenjamimCS** [comment]
Veja se o seu arquivo principal (`index.html` por exemplo) esteja nomeado corretamente conforme o [item 3](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site) da documentação da ferramenta.

**Comment by PedroHenriquePimentel** [comment]
Caraca, acho que é isso mesmo, vlwe
