### ISSUE TITLE
Projeto android

### ISSUE THREAD

**Issue by antony-rodrigues** [gustavoguanabara/html-css#684]
Não consigo acessar meu projeto android pelo github, pois aparece "Error 404".

**Comment by BenjamimCS** [comment]
Certifique-se do arquivo principal estar nomeado de acordo com o [item 3 da seção de criação do site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site).
Caso não resolva, provável Issue #204
