### ISSUE TITLE
html-css

### ISSUE THREAD

**Issue by 98Kevelin** [gustavoguanabara/html-css#685]
Não consigo colocar os exercícios e os desafios no ar, só carrega a página README. Quando digito o caminho para o exercício 001 aparece o erro 404. Coloquei um link no README para o exercício 001 e mesmo assim dá erro.

**Comment by BenjamimCS** [comment]
Os arquivos estão indicados corretamente? Issue #197.

**Comment by BenjamimCS** [comment]
Com a Issue resolvida, por favor, feche a Issue.

**Comment by 98Kevelin** [comment]
Realmente não estava indicado corretamente, obrigada!
