### ISSUE TITLE
HELP-ME!!! Onde encontro os PDF's a partir da aula 21?

### ISSUE THREAD

**Issue by nildomartinsjr** [gustavoguanabara/html-css#688]
No repositório só tem disponível os PDF's do módulo 1 (Aula 1 até a Aula 20 - Mini Projeto Cordel), onde encontro os PDFs a partir da aula 21?
Grato se alguém puder me ajudar.

**Comment by BenjamimCS** [comment]
Issue #357

**Comment by nildomartinsjr** [comment]
Muito obrigado, me ajudou demais.
