### ISSUE TITLE
Imagens Dinâmicas - imagem M não está aparecendo...

### ISSUE THREAD

**Issue by BeatrizDonda** [gustavoguanabara/html-css#69]
Eu chequei cada caracter e tudo está conforme o digitado pelo professor, sendo que o resultado no meu Chrome está sendo: acima de 750px carrega a imagem G, com barra de rolagem lateral.. 
Fiz alguns testes e qdo coloquei a imagem M na tag `<img>` (tirei a G, deixando apenas a P na `<source>`) ela aparece, mas na tag `<source>` não... Pula da P para a G! 😕 

Por favor, se alguém puder me dar uma luz, agradeço muito! 🙏 

As imagens estão exatamente como o prof. mandou, dentro da pasta 'imagens', nos tamanhos e cores certos. Segue o código:

```
<picture>
        <source media="(max-width: 750px)" srcset="imagens/foto-p.png" type="image/png">
        <source media="(max-width: 1050x)" srcset="imagens/foto-m.png" type="image/png">
        <img src="imagens/foto-g.png" alt="Imagem flexível">
</picture>
```

**Comment by mrsaturnino** [comment]
Olá Beatriz!, tudo bem?

Dei uma olhada no seu código e realmente aparenta estar tudo certo.
Até porquê o meu está igualzinho ao seu...

Segue abaixo o meu código:
```
<picture>
        <source media="(max-width: 750px)" srcset="imagens/p-img.png" type="image/png">
        <source media="(max-width: 1050px)" srcset="imagens/m-img.png" type="image/png">
        <img src="imagens/g-img.png" alt="Imagem Flexível">
</picture>
```
Tive um problema com a imagem M também na hora de fazer o código.
Não ao certo se foi isso, mas resolvi simplesmente rodando primeiro o código apenas com a imagem G e P igual está no código, e depois adicionei o código da imagem M entre as duas e atualizei a página novamente.

Espero ter ajudado, esta foi a solução para o meu problema sabe-se lá como.

Segue abaixo as resoluções que coloquei nas minhas imagens:
Imagem G - 1000x1000
Imagem M - 700x700
Imagem P - 300x300

**Comment by BeatrizDonda** [comment]
Oi @mrsaturnino , tdo bem? Obrigada pela atenção!

Pouco depois de postar a Issue, consegui fazer funcionar, porém não entendi exatamente o que ocorreu de errado na primeira tentativa... 

O que eu fiz foi reescrever o código do "zero", em um novo arquivo html, porque não sabia mais o que fazer, e acabou funcionando 🤷‍♀️ Vai entender... Coloquei um do lado do outro pra comparar e estavam iguaizinhos!  

> Não ao certo se foi isso, mas resolvi simplesmente rodando primeiro o código apenas com a imagem G e P igual está no código, e depois adicionei o código da imagem M entre as duas e atualizei a página novamente.

Eu cheguei a fazer isso, mas com o meu não funcionou 😕 Só carregava a M ao colocá-la na tag `<img>` ao invés da `<source>`.

Não lembrei de fechar a issue em seguida, mas foi bom ter a sua resposta aqui porque pode ajudar alguém que se depare com esse problema também! Obrigada mais uma vez
