### ISSUE TITLE
Pdfs do capitulo 22 e 23

### ISSUE THREAD

**Issue by PedroHenriquePimentel** [gustavoguanabara/html-css#697]
Onde estão os pdfs do cap 22 e 23?? So consigo ver os do 1 ate o 21 aqui

**Comment by Afons19** [comment]
Olá, Pedro.
[Acessa este link](https://github.com/gustavoguanabara/html-css/tree/fe6653ecdafa5b7275a5ecb4c36a8ca14f5043e7/aulas-pdf)

 A tua dúvida já foi resolvida na issue #691

**Comment by Afons19** [comment]
Olá, Pedro.
[Acessa este link](https://github.com/gustavoguanabara/html-css/tree/fe6653ecdafa5b7275a5ecb4c36a8ca14f5043e7/aulas-pdf)

 A tua dúvida já foi resolvida na issue #691

**Comment by PedroHenriquePimentel** [comment]
> Olá, Pedro.
> 
> [Acessa este link](https://github.com/gustavoguanabara/html-css/tree/fe6653ecdafa5b7275a5ecb4c36a8ca14f5043e7/aulas-pdf)
> 
> 
> 
>  A tua dúvida já foi resolvida na issue #691 

Vlww

**Comment by BenjamimCS** [comment]
Com a Issue resolvida, por favor, encerre-a.

**Comment by PedroHenriquePimentel** [comment]
vlw gente

**Comment by Anderson-dev-ti** [comment]
> > Olá, Pedro.
> > [Acessa este link](https://github.com/gustavoguanabara/html-css/tree/fe6653ecdafa5b7275a5ecb4c36a8ca14f5043e7/aulas-pdf)
> > A tua dúvida já foi resolvida na issue [#691](https://github.com/gustavoguanabara/html-css/issues/691)
> 
> Vlww

Olá. Na verdade lá só tem o pdf da apostila 24. Você tem a apostila 23? Grato

**Comment by Afons19** [comment]
Olá, @Anderson-dev-ti, a apostilha 23 não está disponível.

O professor não disponibilizou, [fique atento nesta issue](https://github.com/gustavoguanabara/html-css/issues/731#issue-2833623835), a apostilha talvez estará lá quando professor a disponibilizar.
