### ISSUE TITLE
Não consigo executar o handbrake.

### ISSUE THREAD

**Issue by SuhAQueiroz** [gustavoguanabara/html-css#75]
Boa Tarde pessoal, alguém me ajuda! Quando executo o app pede instalação de uma versão de framework, fui direcionada para página de download mas so dá !instalação mal sucedida".
Desde já agradeço!!
![handbrak](https://user-images.githubusercontent.com/65622640/103225057-dad62c80-4907-11eb-9402-581e133c64f9.PNG)

**Comment by klaygueds** [comment]
E porque na tem 4.0 instalado e geralmente este e um componente do windows e instalado pelo update naturalmente em windows update.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by erickoga16** [comment]
Cara não faz sentido já que todos os windows 10 já vem com uma versão do
Net framework. Se for windows 8 ou 7 aí tudo bem, mas se a Suh tá no
windows 10 ela tá tentando instalar um pacote não oficial da Microsoft ou
por algum motivo está com o sistema faltando dar update no sistema.

Em seg, 28 de dez de 2020 14:07, klaygueds <notifications@github.com>
escreveu:

**Comment by SuhAQueiroz** [comment]
@klaygueds @ @erickoga16 Meu Windows é 7, estou verificando se há atualizações importantes no windows update.

**Comment by SuhAQueiroz** [comment]
Depois das atualizações: :/
![Capturar](https://user-images.githubusercontent.com/65622640/103238259-e0903a00-4928-11eb-8367-ef5706c1d69a.PNG)

**Comment by klaygueds** [comment]
A Microsoft  reabilitou  os frameworks  novos pro Windows 7 motivo e a atualização  pro Windows 10, somente atualização de segurança  dos frameworks  sao feitos ate versões  entre 4 / 5, talvez  seja esta falha que vem dando pra você,  se estiver usando alguma  aplicação  que pede frameworks  atuais tenta reverter pro modo de compatibida no seu windows isto deve resolver  se nao e so indo pra atualização  do windows 7 pra Windows 10 ou formatar o sistema  e ja de imediato instar os frameworks .

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by SuhAQueiroz** [comment]
@klaygueds Obrigada !! Vou passar a usar o windows 10 pra não ter mais esses tipos de problemas.

**Comment by SuhAQueiroz** [comment]
Conseguiiiii \o/ O windows update estava atualizando o framework até o 4.7.1, então pesquisei a mais recente e baixei a 4.8 e deu certo !!!!
