### ISSUE TITLE
Exercício 005 não está disponível em nenhum lugar

### ISSUE THREAD

**Issue by PierreVieira** [gustavoguanabara/html-css#78]
No [vídeo](https://youtu.be/aiOEBhozEOg?list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n) em 5:39 o professor fala que o exercício 005 (relacionado a emojis) já deveria ter sido resolvido no capítulo anterior. Entretanto não encontro nenhuma menção a esse exercício nem nos vídeos e nem nos pdfs das aulas.
Alguém poderia me ajudar a desvendar o _**"mistério do desaparecimento do exercício 005"**_?

**Comment by mrsaturnino** [comment]
Olá, Boa noite, Pierre!
Acredito que o "exercicio-005" ao qual o grande mestre se refere seria o de colocar emojis, só que por sinal ele já havia ensinado a colocá-los no "exercicio-002", lá naquela aula de **Parágrafos e quebras de linha**. Portanto, eu imagino que não haveria motivo algum para repetir um exercício  já discutido.
Espero ter ajudado.

**Comment by mrsaturnino** [comment]
Inclusive, você pode encontrar esta parte no material de apoio **05 - Caracteres, parágrafos e quebras de linha**.

**Comment by PierreVieira** [comment]
Sim amigo, eu li o material de apoio que você refere e também fiz o exercício 002, o que estou dizendo é que não tem nenhuma menção desse exercício 005 em específico - tipo um "enunciado" entende? Até mesmo na [pasta de exerícios do github](https://gustavoguanabara.github.io/html-css/exercicios/) o professor pula do exercício 04 para o 06.

**Comment by KamaldeMatos** [comment]
Olá! @PierreVieira, fiz uma reorganização na pasta de exercícios do curso. [Clique aqui para ver](https://github.com/KamaldeMatos/Exercicios-html5-e-css3) Espero que te ajude. O professor Guanabara não pulou do ex004 para o ex006. O que aconteceu foi que o conteúdo do ex005 ele explicou em uma aula anterior por isso a Inexistência da pasta com o ex005, na lista das pastas de exercícios. ele explicou isso em umas das aulas do curso.[Aqui está o vídeo com a aula que mencionei](https://www.youtube.com/watch?v=aiOEBhozEOg&list=PLHz_AreHm4dkZ9-atkcmcBaMZdmLHft8n&index=20) no 5:30 do vídeos você encontra a explicação do professor.
