### ISSUE TITLE
Curso de git e github

### ISSUE THREAD

**Issue by AzenaideFernandes** [gustavoguanabara/html-css#9]
Boa noite professor! O Senhor não vai continuar o curso de git e github? Estava muito legal! Grata

**Comment by christyanbrayan** [comment]
@AzenaideFernandes voltou hj

**Comment by AzenaideFernandes** [comment]
Grata..eu assisti..ótima! Grata

Em qua, 29 de abr de 2020 18:06, Christyan Brayan <notifications@github.com>
escreveu:

**Comment by christyanbrayan** [comment]
@AzenaideFernandes fecha a issue

**Comment by AzenaideFernandes** [comment]
ok grata
