### ISSUE TITLE
É possível tornar público, um repositório que salvei como privado?

### ISSUE THREAD

**Issue by Roberlanderrsilva** [gustavoguanabara/html-css#99]
boa noite,
alguém sabe me dizer se é possível tornar um repositório publico, já que o salvei privado

**Comment by rob-ec** [comment]
É perfeitamente possível @Roberlanderrsilva. No GitHub, navegue até a **página principal do repositório**. No nome do seu repositório, clique em
**Configurações**. As configurações relacionadas a visibilidade são as últmas dessa página, você a indentificará dentro de uma seção com bordas vermelhas. Selecione a opção de **trocar visibilidade** e "tornar público". Após isso basta digitar o que se pede e clicar no botão de confirmação da ação.

ref: [Changing a repository's visibility]( https://docs.github.com/pt/github/administering-a-repository/setting-repository-visibility#)
